--*****************************************************
--	Billing Constraints
--*****************************************************
--/**---------------------------------------------------------------------------------------
--/* Script			: crt_const_billing.sql
--/* Author			: Sridevi Tadisetti  
--/* Product		: Infor SCE Suite 
--/* Component		: Billing - Version 12.7
--/* Date			: 18/06/2025        
--/* Description	: Script to insert Constraints for Billing
--/* RDBMS			: Postgresql
--/* Schema			: Billing
--/* Modification History:
--/*----------------------------------------------------------------------------------------
--/* Modified by	Date			Description    
--/*----------------------------------------------------------------------------------------
--/* 
--/*
--/*---------------------------------------------------------

 -- The query should be run at Postgresql with Postgres user


ALTER TABLE BILLADMIN.BIC_USER 
 ADD CONSTRAINT SYS_C008862 CHECK (USER_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_USER 
 ADD CONSTRAINT SYS_C008863 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_SRCTYPE 
 ADD CONSTRAINT SYS_C008865 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_SRCTYPE 
 ADD CONSTRAINT SYS_C008866 CHECK (SOURCE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_SRCTYPE 
 ADD CONSTRAINT SYS_C008867 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_USER_PROFILE 
 ADD CONSTRAINT SYS_C008869 CHECK (USER_PROFILE_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_USER_PROFILE 
 ADD CONSTRAINT SYS_C008870 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_USER_BILLGRPS 
 ADD CONSTRAINT SYS_C008872 CHECK (USERBILLGRPKEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_USER_BILLGRPS 
 ADD CONSTRAINT SYS_C008873 CHECK (BILL_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_USER_BILLGRPS 
 ADD CONSTRAINT SYS_C008874 CHECK (USER_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_USER_BILLGRPS 
 ADD CONSTRAINT SYS_C008875 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_SYSACT 
 ADD CONSTRAINT SYS_C008877 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_SYSACT 
 ADD CONSTRAINT SYS_C008878 CHECK (SYSTEM_ACTIVITY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_SYSACT 
 ADD CONSTRAINT SYS_C008879 CHECK (SYSTEM_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_SYSACT 
 ADD CONSTRAINT SYS_C008880 CHECK (DESCRIPTION IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_SYSACT 
 ADD CONSTRAINT SYS_C008881 CHECK (LANGUAGE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_SYSACT 
 ADD CONSTRAINT SYS_C008882 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.LOOKUP 
 ADD CONSTRAINT SYS_C008884 CHECK (LOOKUP_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.LOOKUP 
 ADD CONSTRAINT SYS_C008885 CHECK (LOOKUP_CATEGORY_NAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.LOOKUP 
 ADD CONSTRAINT SYS_C008886 CHECK (CODE_STRING IS NOT NULL); 
 
ALTER TABLE BILLADMIN.LOOKUP 
 ADD CONSTRAINT SYS_C008887 CHECK (TEXT_STRING IS NOT NULL); 
 
ALTER TABLE BILLADMIN.LOOKUP 
 ADD CONSTRAINT SYS_C008888 CHECK (LISTORDER IS NOT NULL); 
 
ALTER TABLE BILLADMIN.LOOKUP 
 ADD CONSTRAINT SYS_C008889 CHECK (SYSTEM_MANAGED_FLAG IS NOT NULL); 
 
ALTER TABLE BILLADMIN.LOOKUP 
 ADD CONSTRAINT SYS_C008890 CHECK (REVISION_NUMBER IS NOT NULL); 
 
ALTER TABLE BILLADMIN.LOOKUP 
 ADD CONSTRAINT SYS_C008891 CHECK (OBSOLETE_FLAG IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_UOMLEVEL 
 ADD CONSTRAINT SYS_C008893 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_UOMLEVEL 
 ADD CONSTRAINT SYS_C008894 CHECK (UOM_LEVEL IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_UOMLEVEL 
 ADD CONSTRAINT SYS_C008895 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT 
 ADD CONSTRAINT SYS_C008897 CHECK (CONTRACT_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT 
 ADD CONSTRAINT SYS_C008898 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT 
 ADD CONSTRAINT SYS_C008899 CHECK (EFFECTIVE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT 
 ADD CONSTRAINT SYS_C008900 CHECK (CONTRACT_DESC IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT 
 ADD CONSTRAINT SYS_C008901 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT_DET 
 ADD CONSTRAINT SYS_C008903 CHECK (CONTRACT_DET_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT_DET 
 ADD CONSTRAINT SYS_C008904 CHECK (CONTRACT_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT_DET 
 ADD CONSTRAINT SYS_C008905 CHECK (BILL_TO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT_DET 
 ADD CONSTRAINT SYS_C008906 CHECK (BILL_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT_DET 
 ADD CONSTRAINT SYS_C008907 CHECK (EVENT_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT_DET 
 ADD CONSTRAINT SYS_C008908 CHECK (RATE_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT_DET 
 ADD CONSTRAINT SYS_C008909 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.LOOKUP_TEXT 
 ADD CONSTRAINT SYS_C008911 CHECK (LOOKUP_TEXT_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.LOOKUP_TEXT 
 ADD CONSTRAINT SYS_C008912 CHECK (LOOKUP_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.LOOKUP_TEXT 
 ADD CONSTRAINT SYS_C008913 CHECK (LOCALE_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CORPORATION 
 ADD CONSTRAINT SYS_C008915 CHECK (CORP_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CORPORATION 
 ADD CONSTRAINT SYS_C008916 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_DBS 
 ADD CONSTRAINT SYS_C008918 CHECK (DBS_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_DBS 
 ADD CONSTRAINT SYS_C008919 CHECK (DB_HOST IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_DBS 
 ADD CONSTRAINT SYS_C008920 CHECK (DB_INSTANCE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_DBS 
 ADD CONSTRAINT SYS_C008921 CHECK (DB_PORT IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_DBS 
 ADD CONSTRAINT SYS_C008922 CHECK (DB_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_DBS 
 ADD CONSTRAINT SYS_C008923 CHECK (DB_NAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_DBS 
 ADD CONSTRAINT SYS_C008924 CHECK (DB_USR IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_DBS 
 ADD CONSTRAINT SYS_C008925 CHECK (DB_PWD IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_COST_BALANCE 
 ADD CONSTRAINT SYS_C008927 CHECK (BALANCE_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_COST_BALANCE 
 ADD CONSTRAINT SYS_C008928 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_COST 
 ADD CONSTRAINT SYS_C008930 CHECK (COST_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_COST 
 ADD CONSTRAINT SYS_C008931 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_COST_CODE 
 ADD CONSTRAINT SYS_C008933 CHECK (COST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_COST_CODE 
 ADD CONSTRAINT SYS_C008934 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_COST_DIST 
 ADD CONSTRAINT SYS_C008936 CHECK (COST_DIST_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_COST_DIST 
 ADD CONSTRAINT SYS_C008937 CHECK (COST_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_COST_DIST 
 ADD CONSTRAINT SYS_C008938 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_COST_GROUP 
 ADD CONSTRAINT SYS_C008940 CHECK (COST_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_COST_GROUP 
 ADD CONSTRAINT SYS_C008941 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_SYNC_ITEM 
 ADD CONSTRAINT SYS_C008943 CHECK (ITEM_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_SYNC_ITEM 
 ADD CONSTRAINT SYS_C008944 CHECK (DBS_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_SYNC_ITEM 
 ADD CONSTRAINT SYS_C008945 CHECK (SYNC_ITEM IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_SYNC_ITEM 
 ADD CONSTRAINT SYS_C008946 CHECK (ACTIVE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_SYNC_ITEM 
 ADD CONSTRAINT SYS_C008947 CHECK (DEST_TABLE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_SYNC_ITEM 
 ADD CONSTRAINT SYS_C008948 CHECK (SRC_TABLE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_SYNC_ITEM 
 ADD CONSTRAINT SYS_C008949 CHECK (SRC_WHERE_CLAUSE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_SYNC_ITEM 
 ADD CONSTRAINT SYS_C008950 CHECK (SRC_DT_COLUMN IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_COUNTRY_CURR 
 ADD CONSTRAINT SYS_C008952 CHECK (COUNTRY_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_COUNTRY_CURR 
 ADD CONSTRAINT SYS_C008953 CHECK (CURR_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_COUNTRY_CURR 
 ADD CONSTRAINT SYS_C008954 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CROSS_REF 
 ADD CONSTRAINT SYS_C008956 CHECK (CROSS_REF_QUAL IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CROSS_REF 
 ADD CONSTRAINT SYS_C008957 CHECK (CLIENT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CROSS_REF 
 ADD CONSTRAINT SYS_C008958 CHECK (CROSS_REF_VALUE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CROSS_REF 
 ADD CONSTRAINT SYS_C008959 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008961 CHECK (DATE_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008962 CHECK (ACTUAL_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008963 CHECK (CALENDAR_YR IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008964 CHECK (CALENDAR_QTR IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008965 CHECK (CALENDAR_YR_QTR IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008966 CHECK (CALENDAR_YR_MONTH IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008967 CHECK (CALENDAR_MONTH IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008968 CHECK (CALENDAR_WEEK IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008969 CHECK (CALENDAR_DAY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008970 CHECK (CALENDAR_MONTH_NAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008971 CHECK (DAY_OF_WEEK IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008972 CHECK (LAST_DAY_IN_WEEK IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008973 CHECK (LAST_DAY_IN_MONTH IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008974 CHECK (WEEKDAY_IND IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008975 CHECK (DAY_IN_YEAR IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008976 CHECK (DAY_IN_EPOCH IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD CONSTRAINT SYS_C008977 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CROSS_REF_QUAL 
 ADD CONSTRAINT SYS_C008979 CHECK (CROSS_REF_QUAL IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CROSS_REF_QUAL 
 ADD CONSTRAINT SYS_C008980 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_SQL_SCHED 
 ADD CONSTRAINT SYS_C008982 CHECK (SQL_SCHED_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_SQL_SCHED 
 ADD CONSTRAINT SYS_C008983 CHECK (SQL_ITEM IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_SQL_SCHED 
 ADD CONSTRAINT SYS_C008984 CHECK (SQL_ITEM_ORDER IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_SQL_SCHED 
 ADD CONSTRAINT SYS_C008985 CHECK (SQL_DESC IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_SQL_SCHED 
 ADD CONSTRAINT SYS_C008986 CHECK (SQL_ORDER IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_SQL_SCHED 
 ADD CONSTRAINT SYS_C008987 CHECK (SCHEDULE_ON IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_SQL_SCHED 
 ADD CONSTRAINT SYS_C008988 CHECK (FREQ_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_SQL_SCHED 
 ADD CONSTRAINT SYS_C008989 CHECK (FREQ_INTERVAL IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_SQL_SCHED 
 ADD CONSTRAINT SYS_C008990 CHECK (LAST_RUN_DATETIME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_SQL_SCHED 
 ADD CONSTRAINT SYS_C008991 CHECK (NEXT_RUN_DATETIME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_SQL_SCHED 
 ADD CONSTRAINT SYS_C008992 CHECK (SQL_STMT1 IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CURR_HIST 
 ADD CONSTRAINT SYS_C008994 CHECK (FROM_CURR_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CURR_HIST 
 ADD CONSTRAINT SYS_C008995 CHECK (TO_CURR_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CURR_HIST 
 ADD CONSTRAINT SYS_C008996 CHECK (EXCHANGE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CURR_HIST 
 ADD CONSTRAINT SYS_C008997 CHECK (EXCHANGE_RATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CURR_HIST 
 ADD CONSTRAINT SYS_C008998 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CURRENCY 
 ADD CONSTRAINT SYS_C009000 CHECK (CURR_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CURRENCY 
 ADD CONSTRAINT SYS_C009001 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_DEPARTMENT 
 ADD CONSTRAINT SYS_C009003 CHECK (CORP_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_DEPARTMENT 
 ADD CONSTRAINT SYS_C009004 CHECK (DEPT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_DEPARTMENT 
 ADD CONSTRAINT SYS_C009005 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_EVENT 
 ADD CONSTRAINT SYS_C009007 CHECK (EVENT_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_EVENT 
 ADD CONSTRAINT SYS_C009008 CHECK (EVENT_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_EVENT 
 ADD CONSTRAINT SYS_C009009 CHECK (INVOICE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_EVENT 
 ADD CONSTRAINT SYS_C009010 CHECK (CHARGE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_EVENT 
 ADD CONSTRAINT SYS_C009011 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_DEST_MAP 
 ADD CONSTRAINT SYS_C009013 CHECK (ITEM_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_DEST_MAP 
 ADD CONSTRAINT SYS_C009014 CHECK (DEST_TABLE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_DEST_MAP 
 ADD CONSTRAINT SYS_C009015 CHECK (DEST_COLUMN IS NOT NULL); 
 
ALTER TABLE BILLADMIN.SRC_DEST_MAP 
 ADD CONSTRAINT SYS_C009016 CHECK (ITEM_UNIQUE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_EVENT_GROUP 
 ADD CONSTRAINT SYS_C009018 CHECK (EVENT_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_EVENT_GROUP 
 ADD CONSTRAINT SYS_C009019 CHECK (EVENT_DESC IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_EVENT_GROUP 
 ADD CONSTRAINT SYS_C009020 CHECK (EVENT_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_EVENT_GROUP 
 ADD CONSTRAINT SYS_C009021 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_FACILITY 
 ADD CONSTRAINT SYS_C009023 CHECK (FACILITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_FACILITY 
 ADD CONSTRAINT SYS_C009024 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_FILTER 
 ADD CONSTRAINT SYS_C009026 CHECK (FILTER_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_FILTER 
 ADD CONSTRAINT SYS_C009027 CHECK (FILTER_NAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_FILTER 
 ADD CONSTRAINT SYS_C009028 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_FILTERDETAILS 
 ADD CONSTRAINT SYS_C009030 CHECK (LIST_ORDER IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_FILTERDETAILS 
 ADD CONSTRAINT SYS_C009031 CHECK (FILTER_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_FILTERDETAILS 
 ADD CONSTRAINT SYS_C009032 CHECK (FILTER_DETAIL_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_HIST_CHARGE 
 ADD CONSTRAINT SYS_C009034 CHECK (CHARGE_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_HIST_CHARGE 
 ADD CONSTRAINT SYS_C009035 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_HIST_CHGDIST 
 ADD CONSTRAINT SYS_C009037 CHECK (CHARGE_DIST_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_HIST_CHGDIST 
 ADD CONSTRAINT SYS_C009038 CHECK (BATCH_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_HIST_CHGDIST 
 ADD CONSTRAINT SYS_C009039 CHECK (INVOICE_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_HIST_CHGDIST 
 ADD CONSTRAINT SYS_C009040 CHECK (POST_STATUS IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_HIST_CHGDIST 
 ADD CONSTRAINT SYS_C009041 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_HOLIDAY 
 ADD CONSTRAINT SYS_C009043 CHECK (FACILITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_HOLIDAY 
 ADD CONSTRAINT SYS_C009044 CHECK (HOLIDAY_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_HOLIDAY 
 ADD CONSTRAINT SYS_C009045 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INTERFACE 
 ADD CONSTRAINT SYS_C009047 CHECK (CORP_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INTERFACE 
 ADD CONSTRAINT SYS_C009048 CHECK (INTERFACE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INTERFACE 
 ADD CONSTRAINT SYS_C009049 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY 
 ADD CONSTRAINT SYS_C009051 CHECK (INVENTORY_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY 
 ADD CONSTRAINT SYS_C009052 CHECK (ITEM_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY 
 ADD CONSTRAINT SYS_C009053 CHECK (FACILITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY 
 ADD CONSTRAINT SYS_C009054 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY 
 ADD CONSTRAINT SYS_C009055 CHECK (ITEM IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY 
 ADD CONSTRAINT SYS_C009056 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY_BAL 
 ADD CONSTRAINT SYS_C009058 CHECK (INVENTORY_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY_BAL 
 ADD CONSTRAINT SYS_C009059 CHECK (BALANCE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY_BAL 
 ADD CONSTRAINT SYS_C009060 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY_UDF 
 ADD CONSTRAINT SYS_C009062 CHECK (INVENTORY_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY_UDF 
 ADD CONSTRAINT SYS_C009063 CHECK (UDF_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY_UDF 
 ADD CONSTRAINT SYS_C009064 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY_UOM 
 ADD CONSTRAINT SYS_C009066 CHECK (INVENTORY_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY_UOM 
 ADD CONSTRAINT SYS_C009067 CHECK (UOM_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY_UOM 
 ADD CONSTRAINT SYS_C009068 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVOICE 
 ADD CONSTRAINT SYS_C009070 CHECK (BATCH_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVOICE 
 ADD CONSTRAINT SYS_C009071 CHECK (INVOICE_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVOICE 
 ADD CONSTRAINT SYS_C009072 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVOICE_BATCH 
 ADD CONSTRAINT SYS_C009074 CHECK (BATCH_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVOICE_BATCH 
 ADD CONSTRAINT SYS_C009075 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVOICE_NO 
 ADD CONSTRAINT SYS_C009077 CHECK (SEQ_NUM IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVOICE_NO 
 ADD CONSTRAINT SYS_C009078 CHECK (INVOICE_CNT IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVOICE_NO 
 ADD CONSTRAINT SYS_C009079 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_FILE 
 ADD CONSTRAINT SYS_C009081 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_FILE 
 ADD CONSTRAINT SYS_C009082 CHECK (BATCH_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACCOUNT 
 ADD CONSTRAINT SYS_C009084 CHECK (CORP_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACCOUNT 
 ADD CONSTRAINT SYS_C009085 CHECK (DEPT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACCOUNT 
 ADD CONSTRAINT SYS_C009086 CHECK (ACCT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACCOUNT 
 ADD CONSTRAINT SYS_C009087 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVOICE_TERMS 
 ADD CONSTRAINT SYS_C009089 CHECK (INVOICE_TERMS IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVOICE_TERMS 
 ADD CONSTRAINT SYS_C009090 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY 
 ADD CONSTRAINT SYS_C009092 CHECK (ACTIVITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY 
 ADD CONSTRAINT SYS_C009093 CHECK (FACILITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY 
 ADD CONSTRAINT SYS_C009094 CHECK (ACTIVITY_DESC IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY 
 ADD CONSTRAINT SYS_C009095 CHECK (ACTIVITY_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY 
 ADD CONSTRAINT SYS_C009096 CHECK (INVOICE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY 
 ADD CONSTRAINT SYS_C009097 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FIELD 
 ADD CONSTRAINT SYS_C009099 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FIELD 
 ADD CONSTRAINT SYS_C009100 CHECK (ACTIVITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FIELD 
 ADD CONSTRAINT SYS_C009101 CHECK (FACILITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FIELD 
 ADD CONSTRAINT SYS_C009102 CHECK (TO_FIELD IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FIELD 
 ADD CONSTRAINT SYS_C009103 CHECK (FROM_FIELD IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FIELD 
 ADD CONSTRAINT SYS_C009104 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FILTER 
 ADD CONSTRAINT SYS_C009106 CHECK (FILTER_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FILTER 
 ADD CONSTRAINT SYS_C009107 CHECK (ACTIVITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FILTER 
 ADD CONSTRAINT SYS_C009108 CHECK (FACILITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FILTER 
 ADD CONSTRAINT SYS_C009109 CHECK (FIELD_NAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FILTER 
 ADD CONSTRAINT SYS_C009110 CHECK (OPERATOR IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FILTER 
 ADD CONSTRAINT SYS_C009111 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TASKS 
 ADD CONSTRAINT SYS_C009113 CHECK (ACTIVITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TASKS 
 ADD CONSTRAINT SYS_C009114 CHECK (FACILITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TASKS 
 ADD CONSTRAINT SYS_C009115 CHECK (TASK_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TASKS 
 ADD CONSTRAINT SYS_C009116 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_GROUP 
 ADD CONSTRAINT SYS_C009118 CHECK (ITEM_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_GROUP 
 ADD CONSTRAINT SYS_C009119 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TRANS 
 ADD CONSTRAINT SYS_C009121 CHECK (ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TRANS 
 ADD CONSTRAINT SYS_C009122 CHECK (ACTIVITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TRANS 
 ADD CONSTRAINT SYS_C009123 CHECK (FACILITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TRANS 
 ADD CONSTRAINT SYS_C009124 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_GRPKEY 
 ADD CONSTRAINT SYS_C009126 CHECK (ITEM_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_GRPKEY 
 ADD CONSTRAINT SYS_C009127 CHECK (ITEM IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_GRPKEY 
 ADD CONSTRAINT SYS_C009128 CHECK (PKG IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_GRPKEY 
 ADD CONSTRAINT SYS_C009129 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_GRPKEY 
 ADD CONSTRAINT SYS_C009130 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TYPE 
 ADD CONSTRAINT SYS_C009132 CHECK (ACTIVITY_TYPE_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TYPE 
 ADD CONSTRAINT SYS_C009133 CHECK (ACTIVITY_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TYPE 
 ADD CONSTRAINT SYS_C009134 CHECK (MASTER_TABLE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TYPE 
 ADD CONSTRAINT SYS_C009135 CHECK (MASTER_FIELD IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TYPE 
 ADD CONSTRAINT SYS_C009136 CHECK (MASTER_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TYPE 
 ADD CONSTRAINT SYS_C009137 CHECK (DETAIL_TABLE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TYPE 
 ADD CONSTRAINT SYS_C009138 CHECK (DETAIL_FIELD IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TYPE 
 ADD CONSTRAINT SYS_C009139 CHECK (DETAIL_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TYPE 
 ADD CONSTRAINT SYS_C009140 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTTYPE_FIELD 
 ADD CONSTRAINT SYS_C009142 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTTYPE_FIELD 
 ADD CONSTRAINT SYS_C009143 CHECK (ACTIVITY_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTTYPE_FIELD 
 ADD CONSTRAINT SYS_C009144 CHECK (SQL_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTTYPE_FIELD 
 ADD CONSTRAINT SYS_C009145 CHECK (SQL_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTTYPE_FIELD 
 ADD CONSTRAINT SYS_C009146 CHECK (LEVEL_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTTYPE_FIELD 
 ADD CONSTRAINT SYS_C009147 CHECK (DISPLAY_FLAG IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTTYPE_FIELD 
 ADD CONSTRAINT SYS_C009148 CHECK (SEQNO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTTYPE_FIELD 
 ADD CONSTRAINT SYS_C009149 CHECK (CLAUSE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTTYPE_FIELD 
 ADD CONSTRAINT SYS_C009150 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ACTTYPE_FIELD 
 ADD CONSTRAINT SYS_C009151 CHECK (REVISION_NUMBER IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SQL 
 ADD CONSTRAINT SYS_C009153 CHECK (SQL_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SQL 
 ADD CONSTRAINT SYS_C009154 CHECK (SQL_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SQL 
 ADD CONSTRAINT SYS_C009155 CHECK (SQL_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SQL 
 ADD CONSTRAINT SYS_C009156 CHECK (SQL_DESC IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SQL 
 ADD CONSTRAINT SYS_C009157 CHECK (SQL_ORDER IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SQL 
 ADD CONSTRAINT SYS_C009158 CHECK (SQL_STMT1 IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SQL_UTIL 
 ADD CONSTRAINT SYS_C009160 CHECK (SQL_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SQL_UTIL 
 ADD CONSTRAINT SYS_C009161 CHECK (SQL_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SQL_UTIL 
 ADD CONSTRAINT SYS_C009162 CHECK (SQL_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SQL_UTIL 
 ADD CONSTRAINT SYS_C009163 CHECK (SQL_ORDER IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SQL_UTIL 
 ADD CONSTRAINT SYS_C009164 CHECK (SQL_DESC IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SQL_UTIL 
 ADD CONSTRAINT SYS_C009165 CHECK (SQL_STMT1 IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_UOM 
 ADD CONSTRAINT SYS_C009167 CHECK (ITEM_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_UOM 
 ADD CONSTRAINT SYS_C009168 CHECK (ITEM IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_UOM 
 ADD CONSTRAINT SYS_C009169 CHECK (PKG IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_UOM 
 ADD CONSTRAINT SYS_C009170 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_UOM 
 ADD CONSTRAINT SYS_C009171 CHECK (UOM_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_UOM 
 ADD CONSTRAINT SYS_C009172 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_BILL_GROUP 
 ADD CONSTRAINT SYS_C009174 CHECK (BILL_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_BILL_GROUP 
 ADD CONSTRAINT SYS_C009175 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC 
 ADD CONSTRAINT SYS_C009177 CHECK (MARKUP_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC 
 ADD CONSTRAINT SYS_C009178 CHECK (FACILITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC 
 ADD CONSTRAINT SYS_C009179 CHECK (EFFECTIVE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC 
 ADD CONSTRAINT SYS_C009180 CHECK (EXPIRATION_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC 
 ADD CONSTRAINT SYS_C009181 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_BILLGRP_CUST 
 ADD CONSTRAINT SYS_C009183 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_BILLGRP_CUST 
 ADD CONSTRAINT SYS_C009184 CHECK (BILL_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_BILLGRP_CUST 
 ADD CONSTRAINT SYS_C009185 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC_DET 
 ADD CONSTRAINT SYS_C009187 CHECK (MARKUP_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC_DET 
 ADD CONSTRAINT SYS_C009188 CHECK (CHARGE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC_DET 
 ADD CONSTRAINT SYS_C009189 CHECK (INVOICE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC_DET 
 ADD CONSTRAINT SYS_C009190 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_BILL_GROUP_DET 
 ADD CONSTRAINT SYS_C009192 CHECK (BILL_GRPDET_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_BILL_GROUP_DET 
 ADD CONSTRAINT SYS_C009193 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MEASURE_CONV 
 ADD CONSTRAINT SYS_C009195 CHECK (FROM_MEASURE_UOM IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MEASURE_CONV 
 ADD CONSTRAINT SYS_C009196 CHECK (TO_MEASURE_UOM IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MEASURE_CONV 
 ADD CONSTRAINT SYS_C009197 CHECK (TO_MEASURE_QTY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MEASURE_CONV 
 ADD CONSTRAINT SYS_C009198 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CARRIER_CUST 
 ADD CONSTRAINT SYS_C009200 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CARRIER_CUST 
 ADD CONSTRAINT SYS_C009201 CHECK (CARRIER_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CARRIER_CUST 
 ADD CONSTRAINT SYS_C009202 CHECK (CARRIER_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CARRIER_CUST 
 ADD CONSTRAINT SYS_C009203 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MIN 
 ADD CONSTRAINT SYS_C009205 CHECK (MIN_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MIN 
 ADD CONSTRAINT SYS_C009206 CHECK (MIN_LEVEL IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MIN 
 ADD CONSTRAINT SYS_C009207 CHECK (MIN_CHARGE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MIN 
 ADD CONSTRAINT SYS_C009208 CHECK (EFFECTIVE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MIN 
 ADD CONSTRAINT SYS_C009209 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MIN 
 ADD CONSTRAINT SYS_C009210 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CARRIER_GROUP 
 ADD CONSTRAINT SYS_C009212 CHECK (CARRIER_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CARRIER_GROUP 
 ADD CONSTRAINT SYS_C009213 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MIN_DETAIL 
 ADD CONSTRAINT SYS_C009215 CHECK (MIN_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MIN_DETAIL 
 ADD CONSTRAINT SYS_C009216 CHECK (CHARGE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_MIN_DETAIL 
 ADD CONSTRAINT SYS_C009217 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CARRIER_GRPKEY 
 ADD CONSTRAINT SYS_C009219 CHECK (CARRIER_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CARRIER_GRPKEY 
 ADD CONSTRAINT SYS_C009220 CHECK (CARRIER_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CARRIER_GRPKEY 
 ADD CONSTRAINT SYS_C009221 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_NONNEG_INV 
 ADD CONSTRAINT SYS_C009223 CHECK (ORDER_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_NONNEG_INV 
 ADD CONSTRAINT SYS_C009224 CHECK (BATCH_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_NONNEG_INV 
 ADD CONSTRAINT SYS_C009225 CHECK (INVOICE_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_NONNEG_INV 
 ADD CONSTRAINT SYS_C009226 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE 
 ADD CONSTRAINT SYS_C009228 CHECK (CHARGE_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE 
 ADD CONSTRAINT SYS_C009229 CHECK (BATCH_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE 
 ADD CONSTRAINT SYS_C009230 CHECK (INVOICE_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE 
 ADD CONSTRAINT SYS_C009231 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ORDER_HISTORY 
 ADD CONSTRAINT SYS_C009233 CHECK (ORDER_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ORDER_HISTORY 
 ADD CONSTRAINT SYS_C009234 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ORDER_DETAIL 
 ADD CONSTRAINT SYS_C009236 CHECK (ORDER_DET_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ORDER_DETAIL 
 ADD CONSTRAINT SYS_C009237 CHECK (ORDER_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_ORDER_DETAIL 
 ADD CONSTRAINT SYS_C009238 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_CODE 
 ADD CONSTRAINT SYS_C009240 CHECK (CHARGE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_CODE 
 ADD CONSTRAINT SYS_C009241 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_REMIT 
 ADD CONSTRAINT SYS_C009243 CHECK (REMIT_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_REMIT 
 ADD CONSTRAINT SYS_C009244 CHECK (REMIT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_REMIT 
 ADD CONSTRAINT SYS_C009245 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_DIST 
 ADD CONSTRAINT SYS_C009247 CHECK (CHARGE_DIST_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_DIST 
 ADD CONSTRAINT SYS_C009248 CHECK (BATCH_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_DIST 
 ADD CONSTRAINT SYS_C009249 CHECK (INVOICE_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_DIST 
 ADD CONSTRAINT SYS_C009250 CHECK (POST_STATUS IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_DIST 
 ADD CONSTRAINT SYS_C009251 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PARTNER_CUST 
 ADD CONSTRAINT SYS_C009253 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PARTNER_CUST 
 ADD CONSTRAINT SYS_C009254 CHECK (PARTNER_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PARTNER_CUST 
 ADD CONSTRAINT SYS_C009255 CHECK (PARTNER_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PARTNER_CUST 
 ADD CONSTRAINT SYS_C009256 CHECK (MATCH_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PARTNER_CUST 
 ADD CONSTRAINT SYS_C009257 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_UDF 
 ADD CONSTRAINT SYS_C009259 CHECK (CHARGE_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_UDF 
 ADD CONSTRAINT SYS_C009260 CHECK (FIELD_LABEL IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_UDF 
 ADD CONSTRAINT SYS_C009261 CHECK (INVOICE_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_UDF 
 ADD CONSTRAINT SYS_C009262 CHECK (INVOICE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_UDF 
 ADD CONSTRAINT SYS_C009263 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PARTNER_GROUP 
 ADD CONSTRAINT SYS_C009265 CHECK (PARTNER_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PARTNER_GROUP 
 ADD CONSTRAINT SYS_C009266 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_ACCT 
 ADD CONSTRAINT SYS_C009268 CHECK (CHARGE_ACCT_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_ACCT 
 ADD CONSTRAINT SYS_C009269 CHECK (FACILITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_ACCT 
 ADD CONSTRAINT SYS_C009270 CHECK (CHARGE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_ACCT 
 ADD CONSTRAINT SYS_C009271 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PARTNER_GRPKEY 
 ADD CONSTRAINT SYS_C009273 CHECK (PARTNER_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PARTNER_GRPKEY 
 ADD CONSTRAINT SYS_C009274 CHECK (PARTNER_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PARTNER_GRPKEY 
 ADD CONSTRAINT SYS_C009275 CHECK (MATCH_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PARTNER_GRPKEY 
 ADD CONSTRAINT SYS_C009276 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHRG_ACCT_DET 
 ADD CONSTRAINT SYS_C009278 CHECK (CHARGE_DET_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHRG_ACCT_DET 
 ADD CONSTRAINT SYS_C009279 CHECK (CHARGE_ACCT_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHRG_ACCT_DET 
 ADD CONSTRAINT SYS_C009280 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PERIOD 
 ADD CONSTRAINT SYS_C009282 CHECK (PERIOD_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PERIOD 
 ADD CONSTRAINT SYS_C009283 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHRG_CODE_GRP 
 ADD CONSTRAINT SYS_C009285 CHECK (CHARGE_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CHRG_CODE_GRP 
 ADD CONSTRAINT SYS_C009286 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PERIOD_DETAIL 
 ADD CONSTRAINT SYS_C009288 CHECK (PERIOD_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PERIOD_DETAIL 
 ADD CONSTRAINT SYS_C009289 CHECK (FROM_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PERIOD_DETAIL 
 ADD CONSTRAINT SYS_C009290 CHECK (TO_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PERIOD_DETAIL 
 ADD CONSTRAINT SYS_C009291 CHECK (PERIOD_DAYS IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PERIOD_DETAIL 
 ADD CONSTRAINT SYS_C009292 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFIELD 
 ADD CONSTRAINT SYS_C009294 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFIELD 
 ADD CONSTRAINT SYS_C009295 CHECK (ACTIVITY_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFIELD 
 ADD CONSTRAINT SYS_C009296 CHECK (DB_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFIELD 
 ADD CONSTRAINT SYS_C009297 CHECK (FIELD_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFIELD 
 ADD CONSTRAINT SYS_C009298 CHECK (FIELD_DESC IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFIELD 
 ADD CONSTRAINT SYS_C009299 CHECK (TABLE_NAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFIELD 
 ADD CONSTRAINT SYS_C009300 CHECK (FIELD_NAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFIELD 
 ADD CONSTRAINT SYS_C009301 CHECK (FIELD_LEN IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFIELD 
 ADD CONSTRAINT SYS_C009302 CHECK (LANGUAGE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFIELD 
 ADD CONSTRAINT SYS_C009303 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFILTER 
 ADD CONSTRAINT SYS_C009305 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFILTER 
 ADD CONSTRAINT SYS_C009306 CHECK (ACTIVITY_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFILTER 
 ADD CONSTRAINT SYS_C009307 CHECK (FIELD_NAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFILTER 
 ADD CONSTRAINT SYS_C009308 CHECK (FIELD_DESC IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFILTER 
 ADD CONSTRAINT SYS_C009309 CHECK (TABLE_FIELD IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFILTER 
 ADD CONSTRAINT SYS_C009310 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTTYPE 
 ADD CONSTRAINT SYS_C009312 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTTYPE 
 ADD CONSTRAINT SYS_C009313 CHECK (ACTIVITY_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTTYPE 
 ADD CONSTRAINT SYS_C009314 CHECK (DESCRIPTION IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTTYPE 
 ADD CONSTRAINT SYS_C009315 CHECK (LANGUAGE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTTYPE 
 ADD CONSTRAINT SYS_C009316 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PRINTER 
 ADD CONSTRAINT SYS_C009318 CHECK (SERIAL_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PRINTER 
 ADD CONSTRAINT SYS_C009319 CHECK (USER_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PRINTER 
 ADD CONSTRAINT SYS_C009320 CHECK (PRINTER_NAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_PRINTER 
 ADD CONSTRAINT SYS_C009321 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_BILLEVEL 
 ADD CONSTRAINT SYS_C009323 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_BILLEVEL 
 ADD CONSTRAINT SYS_C009324 CHECK (BILL_LEVEL IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_BILLEVEL 
 ADD CONSTRAINT SYS_C009325 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_QUERY_TEMP 
 ADD CONSTRAINT SYS_C009327 CHECK (SERIAL_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_CHGTYPE 
 ADD CONSTRAINT SYS_C009329 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_CHGTYPE 
 ADD CONSTRAINT SYS_C009330 CHECK (CHARGE_CODE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_CHGTYPE 
 ADD CONSTRAINT SYS_C009331 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RATE 
 ADD CONSTRAINT SYS_C009333 CHECK (RATE_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RATE 
 ADD CONSTRAINT SYS_C009334 CHECK (RATE_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RATE 
 ADD CONSTRAINT SYS_C009335 CHECK (EFFECT_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RATE 
 ADD CONSTRAINT SYS_C009336 CHECK (EXPIRE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RATE 
 ADD CONSTRAINT SYS_C009337 CHECK (CHARGE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RATE 
 ADD CONSTRAINT SYS_C009338 CHECK (RATE_UOM IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RATE 
 ADD CONSTRAINT SYS_C009339 CHECK (FROM_BREAK IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RATE 
 ADD CONSTRAINT SYS_C009340 CHECK (TO_BREAK IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RATE 
 ADD CONSTRAINT SYS_C009341 CHECK (BREAK_UOM IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RATE 
 ADD CONSTRAINT SYS_C009342 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_CHGTYPNO 
 ADD CONSTRAINT SYS_C009344 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_CHGTYPNO 
 ADD CONSTRAINT SYS_C009345 CHECK (CHARGE_TYPE_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_CHGTYPNO 
 ADD CONSTRAINT SYS_C009346 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RATE_GROUP 
 ADD CONSTRAINT SYS_C009348 CHECK (RATE_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RATE_GROUP 
 ADD CONSTRAINT SYS_C009349 CHECK (EFFECT_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RATE_GROUP 
 ADD CONSTRAINT SYS_C009350 CHECK (EXPIRE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RATE_GROUP 
 ADD CONSTRAINT SYS_C009351 CHECK (RATE_GROUP_DESC IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RATE_GROUP 
 ADD CONSTRAINT SYS_C009352 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_COSTALLOC 
 ADD CONSTRAINT SYS_C009354 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_COSTALLOC 
 ADD CONSTRAINT SYS_C009355 CHECK (COST_ALLOC IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_COSTALLOC 
 ADD CONSTRAINT SYS_C009356 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_COSTLVL 
 ADD CONSTRAINT SYS_C009358 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_COSTLVL 
 ADD CONSTRAINT SYS_C009359 CHECK (COST_LEVEL IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_COSTLVL 
 ADD CONSTRAINT SYS_C009360 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_COSTTYPE 
 ADD CONSTRAINT SYS_C009362 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_COSTTYPE 
 ADD CONSTRAINT SYS_C009363 CHECK (COST_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_COSTTYPE 
 ADD CONSTRAINT SYS_C009364 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RECUR_RULE 
 ADD CONSTRAINT SYS_C009366 CHECK (RECUR_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RECUR_RULE 
 ADD CONSTRAINT SYS_C009367 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_DISPFMT 
 ADD CONSTRAINT SYS_C009369 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_DISPFMT 
 ADD CONSTRAINT SYS_C009370 CHECK (DISPLAY_FORMAT IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_DISPFMT 
 ADD CONSTRAINT SYS_C009371 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_REPORT 
 ADD CONSTRAINT SYS_C009373 CHECK (REPORT_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_REPORT 
 ADD CONSTRAINT SYS_C009374 CHECK (REPORT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_REPORT 
 ADD CONSTRAINT SYS_C009375 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_EVENTSPEC 
 ADD CONSTRAINT SYS_C009377 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_EVENTSPEC 
 ADD CONSTRAINT SYS_C009378 CHECK (EVENT_SPECIAL IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_EVENTSPEC 
 ADD CONSTRAINT SYS_C009379 CHECK (INVOICE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_EVENTSPEC 
 ADD CONSTRAINT SYS_C009380 CHECK (ACTIVITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_EVENTSPEC 
 ADD CONSTRAINT SYS_C009381 CHECK (BILL_LEVEL IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_EVENTSPEC 
 ADD CONSTRAINT SYS_C009382 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RPTSEND 
 ADD CONSTRAINT SYS_C009384 CHECK (REPORT_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RPTSEND 
 ADD CONSTRAINT SYS_C009385 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RPTSEND 
 ADD CONSTRAINT SYS_C009386 CHECK (REPORT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_RPTSEND 
 ADD CONSTRAINT SYS_C009387 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_EVENTTYPE 
 ADD CONSTRAINT SYS_C009389 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_EVENTTYPE 
 ADD CONSTRAINT SYS_C009390 CHECK (EVENT_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_EVENTTYPE 
 ADD CONSTRAINT SYS_C009391 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM 
 ADD CONSTRAINT SYS_C009393 CHECK (SYSTEM_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM 
 ADD CONSTRAINT SYS_C009394 CHECK (SYSTEM_DESC IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM 
 ADD CONSTRAINT SYS_C009395 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_FILTFLD 
 ADD CONSTRAINT SYS_C009397 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_FILTFLD 
 ADD CONSTRAINT SYS_C009398 CHECK (FIELD_NAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_FILTFLD 
 ADD CONSTRAINT SYS_C009399 CHECK (FIELD_DESC IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_FILTFLD 
 ADD CONSTRAINT SYS_C009400 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_ACTIVITY 
 ADD CONSTRAINT SYS_C009402 CHECK (SYSTEM_ACTIVITY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_ACTIVITY 
 ADD CONSTRAINT SYS_C009403 CHECK (SYSTEM_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_ACTIVITY 
 ADD CONSTRAINT SYS_C009404 CHECK (ACTIVITY_DESC IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_ACTIVITY 
 ADD CONSTRAINT SYS_C009405 CHECK (ACTIVITY_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_ACTIVITY 
 ADD CONSTRAINT SYS_C009406 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_INVSTATUS 
 ADD CONSTRAINT SYS_C009408 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_INVSTATUS 
 ADD CONSTRAINT SYS_C009409 CHECK (INVOICE_STATUS IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_INVSTATUS 
 ADD CONSTRAINT SYS_C009410 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_FIELD 
 ADD CONSTRAINT SYS_C009412 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_FIELD 
 ADD CONSTRAINT SYS_C009413 CHECK (SYSTEM_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_FIELD 
 ADD CONSTRAINT SYS_C009414 CHECK (ACTIVITY_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_FIELD 
 ADD CONSTRAINT SYS_C009415 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_FILTER 
 ADD CONSTRAINT SYS_C009417 CHECK (SYSTEM_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_FILTER 
 ADD CONSTRAINT SYS_C009418 CHECK (SYSTEM_ACTIVITY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_FILTER 
 ADD CONSTRAINT SYS_C009419 CHECK (FIELD_NAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_FILTER 
 ADD CONSTRAINT SYS_C009420 CHECK (OPERATOR IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_FILTER 
 ADD CONSTRAINT SYS_C009421 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_TASK 
 ADD CONSTRAINT SYS_C009423 CHECK (SYSTEM_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_TASK 
 ADD CONSTRAINT SYS_C009424 CHECK (SYSTEM_ACTIVITY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_TASK 
 ADD CONSTRAINT SYS_C009425 CHECK (TASK_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_TASK 
 ADD CONSTRAINT SYS_C009426 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_INTERTYPE 
 ADD CONSTRAINT SYS_C009428 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_INTERTYPE 
 ADD CONSTRAINT SYS_C009429 CHECK (INTERFACE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_INTERTYPE 
 ADD CONSTRAINT SYS_C009430 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_INVTYPE 
 ADD CONSTRAINT SYS_C009432 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_INVTYPE 
 ADD CONSTRAINT SYS_C009433 CHECK (INVOICE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_INVTYPE 
 ADD CONSTRAINT SYS_C009434 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_TRANS 
 ADD CONSTRAINT SYS_C009436 CHECK (SYSTEM_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_TRANS 
 ADD CONSTRAINT SYS_C009437 CHECK (SYSTEM_ACTIVITY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_TRANS 
 ADD CONSTRAINT SYS_C009438 CHECK (ACTIVITY_CLASS IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_TRANS 
 ADD CONSTRAINT SYS_C009439 CHECK (ACTIVITY_OBJECT IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_TRANS 
 ADD CONSTRAINT SYS_C009440 CHECK (ACTIVITY_ACTION IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_TRANS 
 ADD CONSTRAINT SYS_C009441 CHECK (ACTIVITY_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_TRANS 
 ADD CONSTRAINT SYS_C009442 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_MATCH 
 ADD CONSTRAINT SYS_C009444 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_MATCH 
 ADD CONSTRAINT SYS_C009445 CHECK (MATCH_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_MATCH 
 ADD CONSTRAINT SYS_C009446 CHECK (GROUP_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_MATCH 
 ADD CONSTRAINT SYS_C009447 CHECK (MATCH_DESC IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_MATCH 
 ADD CONSTRAINT SYS_C009448 CHECK (DIRECTION_FLAG IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_MATCH 
 ADD CONSTRAINT SYS_C009449 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_TAX 
 ADD CONSTRAINT SYS_C009451 CHECK (TAX_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_TAX 
 ADD CONSTRAINT SYS_C009452 CHECK (TAX_LEVEL IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_TAX 
 ADD CONSTRAINT SYS_C009453 CHECK (EFFECTIVE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_TAX 
 ADD CONSTRAINT SYS_C009454 CHECK (TAX_CHARGE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_TAX 
 ADD CONSTRAINT SYS_C009455 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_MINLEVEL 
 ADD CONSTRAINT SYS_C009457 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_MINLEVEL 
 ADD CONSTRAINT SYS_C009458 CHECK (MIN_LEVEL IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_MINLEVEL 
 ADD CONSTRAINT SYS_C009459 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_TAX_DETAIL 
 ADD CONSTRAINT SYS_C009461 CHECK (TAX_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_TAX_DETAIL 
 ADD CONSTRAINT SYS_C009462 CHECK (TAX_LEVEL IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_TAX_DETAIL 
 ADD CONSTRAINT SYS_C009463 CHECK (EFFECTIVE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_TAX_DETAIL 
 ADD CONSTRAINT SYS_C009464 CHECK (CHARGE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_TAX_DETAIL 
 ADD CONSTRAINT SYS_C009465 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_PROFILE 
 ADD CONSTRAINT SYS_C009467 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_PROFILE 
 ADD CONSTRAINT SYS_C009468 CHECK (PROFILE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_PROFILE 
 ADD CONSTRAINT SYS_C009469 CHECK (PROFILE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_PROFILE 
 ADD CONSTRAINT SYS_C009470 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_TAX_LEVEL 
 ADD CONSTRAINT SYS_C009472 CHECK (TAX_LEVEL IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_TAX_LEVEL 
 ADD CONSTRAINT SYS_C009473 CHECK (LEVEL_NO IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_TAX_LEVEL 
 ADD CONSTRAINT SYS_C009474 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_REPORT 
 ADD CONSTRAINT SYS_C009476 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_REPORT 
 ADD CONSTRAINT SYS_C009477 CHECK (REPORT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_REPORT 
 ADD CONSTRAINT SYS_C009478 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LANG_TRANSLATION 
 ADD CONSTRAINT SYS_C009480 CHECK (SEQ IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LANG_TRANSLATION 
 ADD CONSTRAINT SYS_C009481 CHECK (LOCALE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LANG_TRANSLATION 
 ADD CONSTRAINT SYS_C009482 CHECK (TABLENAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LANG_TRANSLATION 
 ADD CONSTRAINT SYS_C009483 CHECK (COLUMNNAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LANG_TRANSLATION 
 ADD CONSTRAINT SYS_C009484 CHECK (VALUE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LANG_TRANSLATION 
 ADD CONSTRAINT SYS_C009485 CHECK (WHERECOLUMN IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LANG_TRANSLATION 
 ADD CONSTRAINT SYS_C009486 CHECK (WHEREVALUE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LANG_TRANSLATION 
 ADD CONSTRAINT SYS_C009487 CHECK (TRIM_LENGTH IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_UOM 
 ADD CONSTRAINT SYS_C009489 CHECK (UOM_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_UOM 
 ADD CONSTRAINT SYS_C009490 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_RPTCATG 
 ADD CONSTRAINT SYS_C009492 CHECK (ROW_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_RPTCATG 
 ADD CONSTRAINT SYS_C009493 CHECK (RPT_CATG_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_CODE_RPTCATG 
 ADD CONSTRAINT SYS_C009494 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LOC_GROUP 
 ADD CONSTRAINT SYS_C009496 CHECK (FACILITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LOC_GROUP 
 ADD CONSTRAINT SYS_C009497 CHECK (LOC_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LOC_GROUP 
 ADD CONSTRAINT SYS_C009498 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LOC_GRPKEY 
 ADD CONSTRAINT SYS_C009500 CHECK (LOC_GROUP_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LOC_GRPKEY 
 ADD CONSTRAINT SYS_C009501 CHECK (LOC_GROUP IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LOC_GRPKEY 
 ADD CONSTRAINT SYS_C009502 CHECK (FACILITY_ID IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LOC_GRPKEY 
 ADD CONSTRAINT SYS_C009503 CHECK (LOC_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_LOC_GRPKEY 
 ADD CONSTRAINT SYS_C009504 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVLOC_BAL 
 ADD CONSTRAINT SYS_C009506 CHECK (INVENTORY_KEY IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVLOC_BAL 
 ADD CONSTRAINT SYS_C009507 CHECK (BALANCE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVLOC_BAL 
 ADD CONSTRAINT SYS_C009508 CHECK (LOC_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVLOC_BAL 
 ADD CONSTRAINT SYS_C009509 CHECK (LPN IS NOT NULL); 
 
ALTER TABLE BILLADMIN.BIC_INVLOC_BAL 
 ADD CONSTRAINT SYS_C009510 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD 
 ADD CONSTRAINT SYS_C009512 CHECK (CHARGE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD 
 ADD CONSTRAINT SYS_C009513 CHECK (BILLTO_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD 
 ADD CONSTRAINT SYS_C009514 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD 
 ADD CONSTRAINT SYS_C009515 CHECK (WHSE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD 
 ADD CONSTRAINT SYS_C009516 CHECK (CORP_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD 
 ADD CONSTRAINT SYS_C009517 CHECK (DEPT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD 
 ADD CONSTRAINT SYS_C009518 CHECK (CHARGE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD 
 ADD CONSTRAINT SYS_C009519 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD_AVG 
 ADD CONSTRAINT SYS_C009521 CHECK (CHARGE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD_AVG 
 ADD CONSTRAINT SYS_C009522 CHECK (WHSE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD_AVG 
 ADD CONSTRAINT SYS_C009523 CHECK (CORP_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD_AVG 
 ADD CONSTRAINT SYS_C009524 CHECK (DEPT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD_AVG 
 ADD CONSTRAINT SYS_C009525 CHECK (CHARGE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD_AVG 
 ADD CONSTRAINT SYS_C009526 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW 
 ADD CONSTRAINT SYS_C009528 CHECK (CHARGE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW 
 ADD CONSTRAINT SYS_C009529 CHECK (BILLTO_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW 
 ADD CONSTRAINT SYS_C009530 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW 
 ADD CONSTRAINT SYS_C009531 CHECK (WHSE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW 
 ADD CONSTRAINT SYS_C009532 CHECK (CORP_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW 
 ADD CONSTRAINT SYS_C009533 CHECK (DEPT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW 
 ADD CONSTRAINT SYS_C009534 CHECK (CHARGE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW 
 ADD CONSTRAINT SYS_C009535 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW_AVG 
 ADD CONSTRAINT SYS_C009537 CHECK (CHARGE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW_AVG 
 ADD CONSTRAINT SYS_C009538 CHECK (WHSE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW_AVG 
 ADD CONSTRAINT SYS_C009539 CHECK (CORP_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW_AVG 
 ADD CONSTRAINT SYS_C009540 CHECK (DEPT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW_AVG 
 ADD CONSTRAINT SYS_C009541 CHECK (CHARGE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW_AVG 
 ADD CONSTRAINT SYS_C009542 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM 
 ADD CONSTRAINT SYS_C009544 CHECK (CHARGE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM 
 ADD CONSTRAINT SYS_C009545 CHECK (BILLTO_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM 
 ADD CONSTRAINT SYS_C009546 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM 
 ADD CONSTRAINT SYS_C009547 CHECK (WHSE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM 
 ADD CONSTRAINT SYS_C009548 CHECK (CORP_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM 
 ADD CONSTRAINT SYS_C009549 CHECK (DEPT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM 
 ADD CONSTRAINT SYS_C009550 CHECK (CHARGE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM 
 ADD CONSTRAINT SYS_C009551 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM_AVG 
 ADD CONSTRAINT SYS_C009553 CHECK (CHARGE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM_AVG 
 ADD CONSTRAINT SYS_C009554 CHECK (WHSE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM_AVG 
 ADD CONSTRAINT SYS_C009555 CHECK (CORP_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM_AVG 
 ADD CONSTRAINT SYS_C009556 CHECK (DEPT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM_AVG 
 ADD CONSTRAINT SYS_C009557 CHECK (CHARGE_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM_AVG 
 ADD CONSTRAINT SYS_C009558 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW 
 ADD CONSTRAINT SYS_C009560 CHECK (CHARGE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW 
 ADD CONSTRAINT SYS_C009561 CHECK (BILLTO_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW 
 ADD CONSTRAINT SYS_C009562 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW 
 ADD CONSTRAINT SYS_C009563 CHECK (WHSE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW 
 ADD CONSTRAINT SYS_C009564 CHECK (CORP_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW 
 ADD CONSTRAINT SYS_C009565 CHECK (DEPT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW 
 ADD CONSTRAINT SYS_C009566 CHECK (ACCT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW 
 ADD CONSTRAINT SYS_C009567 CHECK (CHARGE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW 
 ADD CONSTRAINT SYS_C009568 CHECK (CHARGE_UOM IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW 
 ADD CONSTRAINT SYS_C009569 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW_AVG 
 ADD CONSTRAINT SYS_C009571 CHECK (CHARGE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW_AVG 
 ADD CONSTRAINT SYS_C009572 CHECK (WHSE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW_AVG 
 ADD CONSTRAINT SYS_C009573 CHECK (CORP_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW_AVG 
 ADD CONSTRAINT SYS_C009574 CHECK (DEPT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW_AVG 
 ADD CONSTRAINT SYS_C009575 CHECK (ACCT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW_AVG 
 ADD CONSTRAINT SYS_C009576 CHECK (CHARGE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW_AVG 
 ADD CONSTRAINT SYS_C009577 CHECK (CHARGE_UOM IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW_AVG 
 ADD CONSTRAINT SYS_C009578 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM 
 ADD CONSTRAINT SYS_C009580 CHECK (CHARGE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM 
 ADD CONSTRAINT SYS_C009581 CHECK (BILLTO_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM 
 ADD CONSTRAINT SYS_C009582 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM 
 ADD CONSTRAINT SYS_C009583 CHECK (WHSE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM 
 ADD CONSTRAINT SYS_C009584 CHECK (CORP_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM 
 ADD CONSTRAINT SYS_C009585 CHECK (DEPT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM 
 ADD CONSTRAINT SYS_C009586 CHECK (ACCT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM 
 ADD CONSTRAINT SYS_C009587 CHECK (CHARGE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM 
 ADD CONSTRAINT SYS_C009588 CHECK (CHARGE_UOM IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM 
 ADD CONSTRAINT SYS_C009589 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM_AVG 
 ADD CONSTRAINT SYS_C009591 CHECK (CHARGE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM_AVG 
 ADD CONSTRAINT SYS_C009592 CHECK (WHSE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM_AVG 
 ADD CONSTRAINT SYS_C009593 CHECK (CORP_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM_AVG 
 ADD CONSTRAINT SYS_C009594 CHECK (DEPT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM_AVG 
 ADD CONSTRAINT SYS_C009595 CHECK (ACCT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM_AVG 
 ADD CONSTRAINT SYS_C009596 CHECK (CHARGE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM_AVG 
 ADD CONSTRAINT SYS_C009597 CHECK (CHARGE_UOM IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM_AVG 
 ADD CONSTRAINT SYS_C009598 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHARGEALL 
 ADD CONSTRAINT SYS_C009600 CHECK (CHARGE_YEAR IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHARGEALL 
 ADD CONSTRAINT SYS_C009601 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHARGECUST 
 ADD CONSTRAINT SYS_C009603 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHARGECUST 
 ADD CONSTRAINT SYS_C009604 CHECK (CHARGE_YEAR IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHARGECUST 
 ADD CONSTRAINT SYS_C009605 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHARGEDEPT 
 ADD CONSTRAINT SYS_C009607 CHECK (CUST_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHARGEDEPT 
 ADD CONSTRAINT SYS_C009608 CHECK (DEPT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHARGEDEPT 
 ADD CONSTRAINT SYS_C009609 CHECK (DEPT_NAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHARGEDEPT 
 ADD CONSTRAINT SYS_C009610 CHECK (CHARGE_YEAR IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHARGEDEPT 
 ADD CONSTRAINT SYS_C009611 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG3DD 
 ADD CONSTRAINT SYS_C009613 CHECK (CHARGE_DATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG3DD 
 ADD CONSTRAINT SYS_C009614 CHECK (WHSE_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG3DD 
 ADD CONSTRAINT SYS_C009615 CHECK (CORP_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG3DD 
 ADD CONSTRAINT SYS_C009616 CHECK (DEPT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG3DD 
 ADD CONSTRAINT SYS_C009617 CHECK (ACCT_CODE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.PM_S_CHG3DD 
 ADD CONSTRAINT SYS_C009618 CHECK (EDITDATE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.USER_ANONYMIZATION_RULES 
 ADD CONSTRAINT SYS_C009721 CHECK (TABLE_NAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.USER_ANONYMIZATION_RULES 
 ADD CONSTRAINT SYS_C009722 CHECK (COLUMN_NAME IS NOT NULL); 
 
ALTER TABLE BILLADMIN.USER_ANONYMIZATION_RULES 
 ADD CONSTRAINT SYS_C009723 CHECK (ISAUDIT IS NOT NULL); 
 
ALTER TABLE BILLADMIN.USER_ANONYMIZATION_RULES 
 ADD CONSTRAINT SYS_C009724 CHECK (ANONYMIZATION_OPERATION IS NOT NULL); 
 
ALTER TABLE BILLADMIN.USER_ANONYMIZATION_RULES 
 ADD CONSTRAINT SYS_C009725 CHECK (ANONYMIZATION_INSTRUCTION IS NOT NULL); 
 
ALTER TABLE BILLADMIN.USER_ANONYMIZATION_RULES 
 ADD CONSTRAINT SYS_C009726 CHECK (ANONYMIZATION_TYPE IS NOT NULL); 
 
ALTER TABLE BILLADMIN.USER_ANONYMIZATION_RULES 
 ADD CONSTRAINT SYS_C009727 CHECK (RUN_ORDER IS NOT NULL); 
 
ALTER TABLE BILLADMIN.USER_ANONYMIZATION_RULES 
 ADD CONSTRAINT ISAUDIT_CK CHECK (ISAUDIT IN ('Y', 'N')); 
 
ALTER TABLE BILLADMIN.USER_ANONYMIZATION_RULES 
 ADD CONSTRAINT USER_ANONYMIZATION_RULES_CK CHECK (ANONYMIZATION_OPERATION IN ('D', 'U', 'I')); 
 


