--*****************************************************
--	Billing Indexes 
--*****************************************************
--/**---------------------------------------------------------------------------------------
--/* Script			: crt_idx_billing.sql
--/* Author			: Sridevi Tadisetti  
--/* Product		: Infor SCE Suite 
--/* Component		: Billing - Version 12.7
--/* Date			: 18/06/2025        
--/* Description	: Script to create Indexes for Billing
--/* RDBMS			: Postgresql
--/* Schema			: Billing
--/* Modification History:
--/*----------------------------------------------------------------------------------------
--/* Modified by	Date			Description    
--/*----------------------------------------------------------------------------------------
--/*
--/*
--/*-----------------------------------------------------------------------------------------
-- The query should be run at Postgresql with Postgres user


CREATE INDEX BIC_ACTIVITY1 ON BILLADMIN.BIC_ACTIVITY 
 USING  BTREE (ACTIVITY_TYPE ASC) ;
 
CREATE INDEX BIC_ACTIVITY_TYPE1 ON BILLADMIN.BIC_ACTIVITY_TYPE 
 USING  BTREE (ACTIVITY_TYPE ASC) ;
 
CREATE INDEX BIC_BILL_GROUP1 ON BILLADMIN.BIC_BILL_GROUP_DET 
 USING  BTREE (BILL_GROUP ASC) ;
 
CREATE INDEX BIC_CHARGEDIST_CHGNO ON BILLADMIN.BIC_CHARGE_DIST 
 USING  BTREE (CHARGE_NO ASC) ;
 
CREATE INDEX BIC_CHARGEDIST_INVPOSTSTAT ON BILLADMIN.BIC_CHARGE_DIST 
 USING  BTREE (INVOICE_NO ASC, POST_STATUS ASC) ;
 
CREATE INDEX BIC_CHARGE_BATCHINVSTT ON BILLADMIN.BIC_CHARGE 
 USING  BTREE (BATCH_NO ASC, INVOICE_STATUS ASC) ;
 
CREATE INDEX BIC_CHARGE_DIST_BATCHINVSTT ON BILLADMIN.BIC_CHARGE_DIST 
 USING  BTREE (BATCH_NO ASC, INVOICE_STATUS ASC) ;
 
CREATE INDEX BIC_CHARGE_INVTYP ON BILLADMIN.BIC_CHARGE 
 USING  BTREE (INVOICE_TYPE ASC, FACILITY_ID ASC, CUST_CODE ASC, BILL_TO ASC, CHARGE_DATE ASC, CHARGE_CODE ASC) ;
 
CREATE INDEX BIC_CHARGE_MARKORIGCHG ON BILLADMIN.BIC_CHARGE 
 USING  BTREE (MARKUP_ORIG_CHGNO ASC, CHARGE_NO ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_ACTTYPE1 ON BILLADMIN.BIC_CODE_ACTTYPE 
 USING  BTREE (ACTIVITY_TYPE ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_BILLEVEL1 ON BILLADMIN.BIC_CODE_BILLEVEL 
 USING  BTREE (BILL_LEVEL ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_CHGTYPE1 ON BILLADMIN.BIC_CODE_CHGTYPE 
 USING  BTREE (CHARGE_CODE_TYPE ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_CHGTYPNO1 ON BILLADMIN.BIC_CODE_CHGTYPNO 
 USING  BTREE (CHARGE_TYPE_NO ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_COSTALLOC1 ON BILLADMIN.BIC_CODE_COSTALLOC 
 USING  BTREE (COST_ALLOC ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_COSTLVL1 ON BILLADMIN.BIC_CODE_COSTLVL 
 USING  BTREE (COST_LEVEL ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_COSTTYPE1 ON BILLADMIN.BIC_CODE_COSTTYPE 
 USING  BTREE (COST_TYPE ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_DISPFMT1 ON BILLADMIN.BIC_CODE_DISPFMT 
 USING  BTREE (DISPLAY_FORMAT ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_EVENTSPEC1 ON BILLADMIN.BIC_CODE_EVENTSPEC 
 USING  BTREE (EVENT_SPECIAL ASC, INVOICE_TYPE ASC, ACTIVITY_ID ASC, BILL_LEVEL ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_EVENTTYPE1 ON BILLADMIN.BIC_CODE_EVENTTYPE 
 USING  BTREE (EVENT_TYPE ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_FILTFLD1 ON BILLADMIN.BIC_CODE_FILTFLD 
 USING  BTREE (FIELD_NAME ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_INTERTYPE1 ON BILLADMIN.BIC_CODE_INTERTYPE 
 USING  BTREE (INTERFACE_TYPE ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_INVSTATUS1 ON BILLADMIN.BIC_CODE_INVSTATUS 
 USING  BTREE (INVOICE_STATUS ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_INVTYPE1 ON BILLADMIN.BIC_CODE_INVTYPE 
 USING  BTREE (INVOICE_TYPE ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_MATCH1 ON BILLADMIN.BIC_CODE_MATCH 
 USING  BTREE (MATCH_TYPE ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_MINLEVEL1 ON BILLADMIN.BIC_CODE_MINLEVEL 
 USING  BTREE (MIN_LEVEL ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_PROFILE1 ON BILLADMIN.BIC_CODE_PROFILE 
 USING  BTREE (PROFILE_CODE ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_REPORT1 ON BILLADMIN.BIC_CODE_REPORT 
 USING  BTREE (REPORT_CODE ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_RPTCATG1 ON BILLADMIN.BIC_CODE_RPTCATG 
 USING  BTREE (RPT_CATG_CODE ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_SRCTYPE1 ON BILLADMIN.BIC_CODE_SRCTYPE 
 USING  BTREE (SOURCE_TYPE ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_SYSACT1 ON BILLADMIN.BIC_CODE_SYSACT 
 USING  BTREE (SYSTEM_ACTIVITY ASC, SYSTEM_ID ASC, LANGUAGE ASC) ;
 
CREATE UNIQUE INDEX BIC_CODE_UOMLEVEL1 ON BILLADMIN.BIC_CODE_UOMLEVEL 
 USING  BTREE (UOM_LEVEL ASC, LANGUAGE ASC) ;
 
CREATE INDEX BIC_CONTRACTDET_BILLEVENT ON BILLADMIN.BIC_CONTRACT_DET 
 USING  BTREE (BILL_GROUP ASC, EVENT_GROUP ASC) ;
 
CREATE INDEX BIC_CONTRACTDET_CONTRACTKEY1 ON BILLADMIN.BIC_CONTRACT_DET 
 USING  BTREE (CONTRACT_KEY ASC) ;
 
CREATE INDEX BIC_COST_BALANCE_DCG ON BILLADMIN.BIC_COST_BALANCE 
 USING  BTREE (BALANCE_DATE ASC, BALANCE_CODE ASC, FACILITY_ID ASC, CUST_CODE ASC, ITEM_GROUP ASC) ;
 
CREATE INDEX BIC_EVENT1 ON BILLADMIN.BIC_EVENT 
 USING  BTREE (EVENT_GROUP ASC) ;
 
CREATE INDEX BIC_FILE_BIF ON BILLADMIN.BIC_FILE 
 USING  BTREE (BATCH_NO ASC, INVOICE_NO ASC, FILE_NAME ASC) ;
 
CREATE INDEX BIC_FILE_FN ON BILLADMIN.BIC_FILE 
 USING  BTREE (FILE_NAME ASC) ;
 
CREATE INDEX BIC_FILTERDETAILS1 ON BILLADMIN.BIC_FILTERDETAILS 
 USING  BTREE (FILTER_ID ASC, LIST_ORDER ASC) ;
 
CREATE UNIQUE INDEX BIC_INVENTORY1 ON BILLADMIN.BIC_INVENTORY 
 USING  BTREE (FACILITY_ID ASC, CUST_CODE ASC, ITEM ASC, PKG ASC, LOT_CODE ASC) ;
 
CREATE UNIQUE INDEX BIC_MARKDISC1 ON BILLADMIN.BIC_MARKDISC 
 USING  BTREE (FACILITY_ID ASC, EFFECTIVE_DATE ASC, EXPIRATION_DATE ASC, CUST_CODE ASC, BILL_TO ASC, BILL_GROUP ASC) ;
 
CREATE UNIQUE INDEX BIC_MIN1 ON BILLADMIN.BIC_MIN 
 USING  BTREE (MIN_LEVEL ASC, MIN_CHARGE_CODE ASC, EFFECTIVE_DATE ASC, CUST_CODE ASC, INVOICE_TYPE ASC, ACTIVITY_ID ASC, FACILITY_ID ASC, BILL_TO ASC, BILL_GROUP ASC) ;
 
CREATE INDEX BIC_ORDER_DETAIL1 ON BILLADMIN.BIC_ORDER_DETAIL 
 USING  BTREE (ORDER_KEY ASC) ;
 
CREATE INDEX BIC_ORDER_HISTORY1 ON BILLADMIN.BIC_ORDER_HISTORY 
 USING  BTREE (FACILITY_ID ASC, ORDER_NO ASC, CUST_CODE ASC, ACTIVITY_ID ASC, ORDER_TYPE ASC, DC_ID ASC) ;
 
CREATE INDEX BIC_RATE_GCEEU ON BILLADMIN.BIC_RATE 
 USING  BTREE (RATE_GROUP ASC, CHARGE_CODE ASC, EFFECT_DATE ASC, EXPIRE_DATE ASC, RATE_UOM ASC) ;
 
CREATE UNIQUE INDEX BIC_SQL1 ON BILLADMIN.BIC_SQL 
 USING  BTREE (SQL_TYPE ASC, SQL_CODE ASC) ;
 
CREATE UNIQUE INDEX BIC_SQL_UTIL1 ON BILLADMIN.BIC_SQL_UTIL 
 USING  BTREE (SQL_TYPE ASC, SQL_CODE ASC, SQL_ORDER ASC) ;
 
CREATE UNIQUE INDEX BIC_TAX_LEVEL1 ON BILLADMIN.BIC_TAX_LEVEL 
 USING  BTREE (TAX_LEVEL ASC, LEVEL_NO ASC) ;
 
CREATE INDEX BIC_USER_PROFILE1 ON BILLADMIN.BIC_USER_PROFILE 
 USING  BTREE (PROFILE_CODE ASC, USER_CODE ASC, FACILITY_ID ASC, CUST_CODE ASC, CHARGE_CODE ASC) ;
 
CREATE UNIQUE INDEX SQL_SCHED1 ON BILLADMIN.PM_SQL_SCHED 
 USING  BTREE (SQL_ITEM ASC, SQL_ORDER ASC) ;
 
CREATE UNIQUE INDEX SRC_DBS_UNIQUE ON BILLADMIN.SRC_DBS 
 USING  BTREE (DB_HOST ASC, DB_INSTANCE ASC, DB_PORT ASC, DB_NAME ASC) ;
 
CREATE UNIQUE INDEX SRC_SYNC_ITEM_UNIQUE ON BILLADMIN.SRC_SYNC_ITEM 
 USING  BTREE (DBS_KEY ASC, SYNC_ITEM ASC) ;
 


