--*****************************************************
--	Billing Foreign Keys
--*****************************************************
--/**---------------------------------------------------------------------------------------
--/* Script			: crt_fk_billing.sql
--/* Author			: Sridevi Tadisetti  
--/* Product		: Infor SCE Suite 
--/* Component		: Billing - Version 12.7
--/* Date			: 18/06/2025        
--/* Description	: Script to insert foreign keys for Billing
--/* RDBMS			: Postgresql
--/* Schema			: Billing
--/* Modification History:
--/*----------------------------------------------------------------------------------------
--/* Modified by	Date			Description    
--/*----------------------------------------------------------------------------------------
--/* 
--/*
--/*-----------------------------------------------------------------------------------------


-- The query should be run at Postgresql with Postgres user

-- Script to create Foreign Keys belongs to BILLADMIN role.

ALTER TABLE BILLADMIN.BIC_ACCOUNT ADD CONSTRAINT FK_BIC_ACCT_CORP  
 FOREIGN  KEY (CORP_CODE) REFERENCES BILLADMIN.BIC_CORPORATION (CORP_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_ACCOUNT ADD CONSTRAINT FK_BIC_ACCT_DEPT  
 FOREIGN  KEY (CORP_CODE, DEPT_CODE) REFERENCES BILLADMIN.BIC_DEPARTMENT (CORP_CODE, DEPT_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY ADD CONSTRAINT FK_BIC_ACT_FACILITY  
 FOREIGN  KEY (FACILITY_ID) REFERENCES BILLADMIN.BIC_FACILITY (FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY ADD CONSTRAINT FK_BIC_ACT_SYSTEM  
 FOREIGN  KEY (SYSTEM_ID) REFERENCES BILLADMIN.BIC_SYSTEM (SYSTEM_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FIELD ADD CONSTRAINT FK_BIC_ACTFIELD_BIC_ACT  
 FOREIGN  KEY (ACTIVITY_ID, FACILITY_ID) REFERENCES BILLADMIN.BIC_ACTIVITY (ACTIVITY_ID, FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FILTER ADD CONSTRAINT FK_BIC_ACTFIL_BIC_ACT  
 FOREIGN  KEY (ACTIVITY_ID, FACILITY_ID) REFERENCES BILLADMIN.BIC_ACTIVITY (ACTIVITY_ID, FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TASKS ADD CONSTRAINT FK_BIC_ACTTKS_FACILITY  
 FOREIGN  KEY (FACILITY_ID) REFERENCES BILLADMIN.BIC_FACILITY (FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TRANS ADD CONSTRAINT FK_BIC_ACTTRN_FACACT  
 FOREIGN  KEY (ACTIVITY_ID, FACILITY_ID) REFERENCES BILLADMIN.BIC_ACTIVITY (ACTIVITY_ID, FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TRANS ADD CONSTRAINT FK_BIC_ACTTRN_FACILITY  
 FOREIGN  KEY (FACILITY_ID) REFERENCES BILLADMIN.BIC_FACILITY (FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_BILL_GROUP_DET ADD CONSTRAINT FK_BIC_BILLGROUP  
 FOREIGN  KEY (BILL_GROUP) REFERENCES BILLADMIN.BIC_BILL_GROUP (BILL_GROUP) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_BILL_GROUP_DET ADD CONSTRAINT FK_BIC_BILLGRP_CARGRP  
 FOREIGN  KEY (CARRIER_GROUP) REFERENCES BILLADMIN.BIC_CARRIER_GROUP (CARRIER_GROUP) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_BILL_GROUP_DET ADD CONSTRAINT FK_BIC_BILLGRP_FACILITY  
 FOREIGN  KEY (FACILITY_ID) REFERENCES BILLADMIN.BIC_FACILITY (FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_BILL_GROUP_DET ADD CONSTRAINT FK_BIC_BILLGRP_ITEMGRP  
 FOREIGN  KEY (ITEM_GROUP) REFERENCES BILLADMIN.BIC_ITEM_GROUP (ITEM_GROUP) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_BILL_GROUP_DET ADD CONSTRAINT FK_BIC_BILLGRP_PGRP  
 FOREIGN  KEY (PARTNER_GROUP) REFERENCES BILLADMIN.BIC_PARTNER_GROUP (PARTNER_GROUP) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CHARGE ADD CONSTRAINT FK_BIC_CHARGE_ACT  
 FOREIGN  KEY (ACTIVITY_ID, FACILITY_ID) REFERENCES BILLADMIN.BIC_ACTIVITY (ACTIVITY_ID, FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CHARGE ADD CONSTRAINT FK_BIC_CHARGE_CHRG  
 FOREIGN  KEY (CHARGE_CODE) REFERENCES BILLADMIN.BIC_CHARGE_CODE (CHARGE_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CHARGE ADD CONSTRAINT FK_BIC_CHARGE_FACILITY  
 FOREIGN  KEY (FACILITY_ID) REFERENCES BILLADMIN.BIC_FACILITY (FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CHARGE ADD CONSTRAINT FK_BIC_CHARGE_UOM  
 FOREIGN  KEY (CHARGE_UOM) REFERENCES BILLADMIN.BIC_UOM (UOM_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_ACCT ADD CONSTRAINT FK_BIC_CHG_ACCT_BGRP  
 FOREIGN  KEY (BILL_GROUP) REFERENCES BILLADMIN.BIC_BILL_GROUP (BILL_GROUP) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_ACCT ADD CONSTRAINT FK_BIC_CHG_ACCT_CODE  
 FOREIGN  KEY (CHARGE_CODE) REFERENCES BILLADMIN.BIC_CHARGE_CODE (CHARGE_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_ACCT ADD CONSTRAINT FK_BIC_CHG_ACCT_FAC  
 FOREIGN  KEY (FACILITY_ID) REFERENCES BILLADMIN.BIC_FACILITY (FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_CODE ADD CONSTRAINT FK_BIC_CHG_CODE_CRCDA  
 FOREIGN  KEY (DEF_CR_CORP, DEF_CR_DEPT, DEF_CR_ACCT) REFERENCES BILLADMIN.BIC_ACCOUNT (CORP_CODE, DEPT_CODE, ACCT_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_CODE ADD CONSTRAINT FK_BIC_CHG_CODE_DBCDA  
 FOREIGN  KEY (DEF_DB_CORP, DEF_DB_DEPT, DEF_DB_ACCT) REFERENCES BILLADMIN.BIC_ACCOUNT (CORP_CODE, DEPT_CODE, ACCT_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_CODE ADD CONSTRAINT FK_BIC_CHG_CODE_GROUP  
 FOREIGN  KEY (CHARGE_GROUP) REFERENCES BILLADMIN.BIC_CHRG_CODE_GRP (CHARGE_GROUP) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CHRG_ACCT_DET ADD CONSTRAINT FK_BIC_CHRG_DET_CRCDA  
 FOREIGN  KEY (CR_CORP, CR_DEPT, CR_ACCT) REFERENCES BILLADMIN.BIC_ACCOUNT (CORP_CODE, DEPT_CODE, ACCT_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CHRG_ACCT_DET ADD CONSTRAINT FK_BIC_CHRG_DET_DBCDA  
 FOREIGN  KEY (DB_CORP, DB_DEPT, DB_ACCT) REFERENCES BILLADMIN.BIC_ACCOUNT (CORP_CODE, DEPT_CODE, ACCT_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT ADD CONSTRAINT FK_BIC_CONTRACT  
 FOREIGN  KEY (INVOICE_TERMS) REFERENCES BILLADMIN.BIC_INVOICE_TERMS (INVOICE_TERMS) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT_DET ADD CONSTRAINT FK_BIC_CONTRACT_BILLGRP  
 FOREIGN  KEY (BILL_GROUP) REFERENCES BILLADMIN.BIC_BILL_GROUP (BILL_GROUP) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT_DET ADD CONSTRAINT FK_BIC_CONTRACT_EVENTGRP  
 FOREIGN  KEY (EVENT_GROUP) REFERENCES BILLADMIN.BIC_EVENT_GROUP (EVENT_GROUP) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT_DET ADD CONSTRAINT FK_BIC_CONTRACT_FAC  
 FOREIGN  KEY (FACILITY_ID) REFERENCES BILLADMIN.BIC_FACILITY (FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_COST_CODE ADD CONSTRAINT FK_BIC_COST_CODE_CRCDA  
 FOREIGN  KEY (DEF_CR_CORP, DEF_CR_DEPT, DEF_CR_ACCT) REFERENCES BILLADMIN.BIC_ACCOUNT (CORP_CODE, DEPT_CODE, ACCT_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_COST_CODE ADD CONSTRAINT FK_BIC_COST_CODE_DBCDA  
 FOREIGN  KEY (DEF_DB_CORP, DEF_DB_DEPT, DEF_DB_ACCT) REFERENCES BILLADMIN.BIC_ACCOUNT (CORP_CODE, DEPT_CODE, ACCT_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_COST_CODE ADD CONSTRAINT FK_BIC_COST_GROUP  
 FOREIGN  KEY (COST_GROUP) REFERENCES BILLADMIN.BIC_COST_GROUP (COST_GROUP) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_COUNTRY_CURR ADD CONSTRAINT FK_BIC_CTRY_CURR_CURR  
 FOREIGN  KEY (CURR_CODE) REFERENCES BILLADMIN.BIC_CURRENCY (CURR_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CURR_HIST ADD CONSTRAINT FK_BIC_CURR_HIST_FROM  
 FOREIGN  KEY (FROM_CURR_CODE) REFERENCES BILLADMIN.BIC_CURRENCY (CURR_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_CURR_HIST ADD CONSTRAINT FK_BIC_CURR_HIST_TO  
 FOREIGN  KEY (TO_CURR_CODE) REFERENCES BILLADMIN.BIC_CURRENCY (CURR_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_DEPARTMENT ADD CONSTRAINT FK_BIC_DEPT_CORP  
 FOREIGN  KEY (CORP_CODE) REFERENCES BILLADMIN.BIC_CORPORATION (CORP_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_EVENT ADD CONSTRAINT FK_BIC_EVENT_BILLUOM  
 FOREIGN  KEY (BILL_UOM) REFERENCES BILLADMIN.BIC_UOM (UOM_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_EVENT ADD CONSTRAINT FK_BIC_EVENT_CHRG  
 FOREIGN  KEY (CHARGE_CODE) REFERENCES BILLADMIN.BIC_CHARGE_CODE (CHARGE_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_EVENT ADD CONSTRAINT FK_BIC_EVENT_FROMPER  
 FOREIGN  KEY (FROM_PERIOD) REFERENCES BILLADMIN.BIC_PERIOD (PERIOD_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_EVENT ADD CONSTRAINT FK_BIC_EVENT_GROUP  
 FOREIGN  KEY (EVENT_GROUP) REFERENCES BILLADMIN.BIC_EVENT_GROUP (EVENT_GROUP) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_EVENT ADD CONSTRAINT FK_BIC_EVENT_GRPER  
 FOREIGN  KEY (GRACE_PERIOD) REFERENCES BILLADMIN.BIC_PERIOD (PERIOD_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_EVENT ADD CONSTRAINT FK_BIC_EVENT_OFPER  
 FOREIGN  KEY (OF_PERIOD) REFERENCES BILLADMIN.BIC_PERIOD (PERIOD_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_EVENT ADD CONSTRAINT FK_BIC_EVENT_RECUR  
 FOREIGN  KEY (RECUR_CODE) REFERENCES BILLADMIN.BIC_RECUR_RULE (RECUR_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_EVENT ADD CONSTRAINT FK_BIC_EVENT_TOPER  
 FOREIGN  KEY (TO_PERIOD) REFERENCES BILLADMIN.BIC_PERIOD (PERIOD_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_FACILITY ADD CONSTRAINT FK_BIC_FACILITY_CUBEUOM  
 FOREIGN  KEY (CUBE_UOM) REFERENCES BILLADMIN.BIC_UOM (UOM_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_FACILITY ADD CONSTRAINT FK_BIC_FACILITY_CURR  
 FOREIGN  KEY (CURR_CODE) REFERENCES BILLADMIN.BIC_CURRENCY (CURR_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_FACILITY ADD CONSTRAINT FK_BIC_FACILITY_DIMUOM  
 FOREIGN  KEY (DIMEN_UOM) REFERENCES BILLADMIN.BIC_UOM (UOM_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_FACILITY ADD CONSTRAINT FK_BIC_FACILITY_SYSTEM  
 FOREIGN  KEY (SYSTEM_ID) REFERENCES BILLADMIN.BIC_SYSTEM (SYSTEM_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_FACILITY ADD CONSTRAINT FK_BIC_FACILITY_WGTUOM  
 FOREIGN  KEY (WGT_UOM) REFERENCES BILLADMIN.BIC_UOM (UOM_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_FILTERDETAILS ADD CONSTRAINT FK_BIC_FILTERDETAILS_FILTER  
 FOREIGN  KEY (FILTER_ID) REFERENCES BILLADMIN.BIC_FILTER (FILTER_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_HOLIDAY ADD CONSTRAINT FK_BIC_HOLIDAY_FACILITY  
 FOREIGN  KEY (FACILITY_ID) REFERENCES BILLADMIN.BIC_FACILITY (FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_INTERFACE ADD CONSTRAINT FK_BIC_INTER_CORP  
 FOREIGN  KEY (CORP_CODE) REFERENCES BILLADMIN.BIC_CORPORATION (CORP_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY_BAL ADD CONSTRAINT FK_BIC_INVENTORY_BAL  
 FOREIGN  KEY (INVENTORY_KEY) REFERENCES BILLADMIN.BIC_INVENTORY (INVENTORY_KEY) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY_UDF ADD CONSTRAINT FK_BIC_INVENTORY_UDF  
 FOREIGN  KEY (INVENTORY_KEY) REFERENCES BILLADMIN.BIC_INVENTORY (INVENTORY_KEY) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY_UOM ADD CONSTRAINT FK_BIC_INVENTORY_UOM  
 FOREIGN  KEY (INVENTORY_KEY) REFERENCES BILLADMIN.BIC_INVENTORY (INVENTORY_KEY) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_INVLOC_BAL ADD CONSTRAINT FK_BIC_INVLOC_BAL  
 FOREIGN  KEY (INVENTORY_KEY) REFERENCES BILLADMIN.BIC_INVENTORY (INVENTORY_KEY) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_INVOICE ADD CONSTRAINT FK_BIC_INV_CURR  
 FOREIGN  KEY (INV_CURR_CODE) REFERENCES BILLADMIN.BIC_CURRENCY (CURR_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_INVOICE ADD CONSTRAINT FK_BIC_INV_CUSTCURR  
 FOREIGN  KEY (CUST_CURR_CODE) REFERENCES BILLADMIN.BIC_CURRENCY (CURR_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_INVOICE ADD CONSTRAINT FK_BIC_INV_FAC  
 FOREIGN  KEY (FACILITY_ID) REFERENCES BILLADMIN.BIC_FACILITY (FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_INVOICE ADD CONSTRAINT FK_BIC_INV_TERMS  
 FOREIGN  KEY (INVOICE_TERMS) REFERENCES BILLADMIN.BIC_INVOICE_TERMS (INVOICE_TERMS) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_ITEM_UOM ADD CONSTRAINT FK_BIC_ITEM_UCUOM  
 FOREIGN  KEY (CUBE_UOM) REFERENCES BILLADMIN.BIC_UOM (UOM_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_ITEM_UOM ADD CONSTRAINT FK_BIC_ITEM_UWUOM  
 FOREIGN  KEY (WGT_UOM) REFERENCES BILLADMIN.BIC_UOM (UOM_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC ADD CONSTRAINT FK_BIC_MARKDISC_BILLGRP  
 FOREIGN  KEY (BILL_GROUP) REFERENCES BILLADMIN.BIC_BILL_GROUP (BILL_GROUP) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC ADD CONSTRAINT FK_BIC_MARKDISC_FACILITY  
 FOREIGN  KEY (FACILITY_ID) REFERENCES BILLADMIN.BIC_FACILITY (FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC_DET ADD CONSTRAINT FK_BIC_MARKDISC_CHG  
 FOREIGN  KEY (CHARGE_CODE) REFERENCES BILLADMIN.BIC_CHARGE_CODE (CHARGE_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC_DET ADD CONSTRAINT FK_BIC_MARKDISC_CRCDA  
 FOREIGN  KEY (CR_CORP, CR_DEPT, CR_ACCT) REFERENCES BILLADMIN.BIC_ACCOUNT (CORP_CODE, DEPT_CODE, ACCT_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC_DET ADD CONSTRAINT FK_BIC_MARKDISC_DBCDA  
 FOREIGN  KEY (DB_CORP, DB_DEPT, DB_ACCT) REFERENCES BILLADMIN.BIC_ACCOUNT (CORP_CODE, DEPT_CODE, ACCT_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC_DET ADD CONSTRAINT FK_BIC_MARKDISC_KEY  
 FOREIGN  KEY (MARKUP_KEY) REFERENCES BILLADMIN.BIC_MARKDISC (MARKUP_KEY) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC_DET ADD CONSTRAINT FK_BIC_MARKDISC_MKCHG  
 FOREIGN  KEY (MK_CHARGE_CODE) REFERENCES BILLADMIN.BIC_CHARGE_CODE (CHARGE_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_MEASURE_CONV ADD CONSTRAINT FK_BIC_MEASURE_FROM  
 FOREIGN  KEY (FROM_MEASURE_UOM) REFERENCES BILLADMIN.BIC_UOM (UOM_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_MEASURE_CONV ADD CONSTRAINT FK_BIC_MEASURE_TO  
 FOREIGN  KEY (TO_MEASURE_UOM) REFERENCES BILLADMIN.BIC_UOM (UOM_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_MIN ADD CONSTRAINT FK_BIC_MIN_BILLGRP  
 FOREIGN  KEY (BILL_GROUP) REFERENCES BILLADMIN.BIC_BILL_GROUP (BILL_GROUP) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_MIN ADD CONSTRAINT FK_BIC_MIN_CHG  
 FOREIGN  KEY (MIN_CHARGE_CODE) REFERENCES BILLADMIN.BIC_CHARGE_CODE (CHARGE_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_MIN ADD CONSTRAINT FK_BIC_MIN_FAC  
 FOREIGN  KEY (FACILITY_ID) REFERENCES BILLADMIN.BIC_FACILITY (FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_MIN ADD CONSTRAINT FK_BIC_MIN_UOM  
 FOREIGN  KEY (MIN_UOM) REFERENCES BILLADMIN.BIC_UOM (UOM_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_MIN_DETAIL ADD CONSTRAINT FK_BIC_MIN_DET_CHG  
 FOREIGN  KEY (CHARGE_CODE) REFERENCES BILLADMIN.BIC_CHARGE_CODE (CHARGE_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_MIN_DETAIL ADD CONSTRAINT FK_BIC_MIN_DET_KEY  
 FOREIGN  KEY (MIN_KEY) REFERENCES BILLADMIN.BIC_MIN (MIN_KEY) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_PERIOD_DETAIL ADD CONSTRAINT FK_BIC_PERIOD_DETAIL  
 FOREIGN  KEY (PERIOD_CODE) REFERENCES BILLADMIN.BIC_PERIOD (PERIOD_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_PRINTER ADD CONSTRAINT FK_BIC_PRINTER_USER  
 FOREIGN  KEY (USER_CODE) REFERENCES BILLADMIN.BIC_USER (USER_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_RATE ADD CONSTRAINT FK_BIC_RATEBRK_UOM  
 FOREIGN  KEY (BREAK_UOM) REFERENCES BILLADMIN.BIC_UOM (UOM_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_RATE ADD CONSTRAINT FK_BIC_RATE_CHG  
 FOREIGN  KEY (CHARGE_CODE) REFERENCES BILLADMIN.BIC_CHARGE_CODE (CHARGE_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_RATE ADD CONSTRAINT FK_BIC_RATE_GROUP  
 FOREIGN  KEY (RATE_GROUP, EFFECT_DATE, EXPIRE_DATE) REFERENCES BILLADMIN.BIC_RATE_GROUP (RATE_GROUP, EFFECT_DATE, EXPIRE_DATE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_RATE ADD CONSTRAINT FK_BIC_RATE_UOM  
 FOREIGN  KEY (RATE_UOM) REFERENCES BILLADMIN.BIC_UOM (UOM_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_RECUR_RULE ADD CONSTRAINT FK_BIC_RECUR_AFTPER  
 FOREIGN  KEY (AFTER_PERIOD) REFERENCES BILLADMIN.BIC_PERIOD (PERIOD_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_RECUR_RULE ADD CONSTRAINT FK_BIC_RECUR_ONPER  
 FOREIGN  KEY (ON_PERIOD) REFERENCES BILLADMIN.BIC_PERIOD (PERIOD_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_REPORT ADD CONSTRAINT FK_BIC_REPORT_FAC  
 FOREIGN  KEY (FACILITY_ID) REFERENCES BILLADMIN.BIC_FACILITY (FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_RPTSEND ADD CONSTRAINT FK_BIC_RPTSEND_FAC  
 FOREIGN  KEY (FACILITY_ID) REFERENCES BILLADMIN.BIC_FACILITY (FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_TAX ADD CONSTRAINT FK_BIC_TAX_CHG  
 FOREIGN  KEY (TAX_CHARGE_CODE) REFERENCES BILLADMIN.BIC_CHARGE_CODE (CHARGE_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_TAX ADD CONSTRAINT FK_BIC_TAX_LVL  
 FOREIGN  KEY (TAX_LEVEL) REFERENCES BILLADMIN.BIC_TAX_LEVEL (TAX_LEVEL) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_TAX ADD CONSTRAINT FK_BIC_TAX_UOM  
 FOREIGN  KEY (TAX_UOM) REFERENCES BILLADMIN.BIC_UOM (UOM_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_TAX_DETAIL ADD CONSTRAINT FK_BIC_TAX_DET_CHG  
 FOREIGN  KEY (CHARGE_CODE) REFERENCES BILLADMIN.BIC_CHARGE_CODE (CHARGE_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_TAX_DETAIL ADD CONSTRAINT FK_BIC_TAX_DET_KEY  
 FOREIGN  KEY (TAX_GROUP, TAX_LEVEL, EFFECTIVE_DATE) REFERENCES BILLADMIN.BIC_TAX (TAX_GROUP, TAX_LEVEL, EFFECTIVE_DATE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_TAX_DETAIL ADD CONSTRAINT FK_BIC_TAX_DET_LVL  
 FOREIGN  KEY (TAX_LEVEL) REFERENCES BILLADMIN.BIC_TAX_LEVEL (TAX_LEVEL) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_UOM ADD CONSTRAINT FK_BIC_UOM_MUOM  
 FOREIGN  KEY (MEASURE_UOM) REFERENCES BILLADMIN.BIC_UOM (UOM_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_USER_BILLGRPS ADD CONSTRAINT FK_BIC_USER_BGP_BG  
 FOREIGN  KEY (BILL_GROUP) REFERENCES BILLADMIN.BIC_BILL_GROUP (BILL_GROUP) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_USER_BILLGRPS ADD CONSTRAINT FK_BIC_USER_BGP_BU  
 FOREIGN  KEY (USER_CODE) REFERENCES BILLADMIN.BIC_USER (USER_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_USER_PROFILE ADD CONSTRAINT FK_BIC_PROFILE_CHGCD  
 FOREIGN  KEY (CHARGE_CODE) REFERENCES BILLADMIN.BIC_CHARGE_CODE (CHARGE_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_USER_PROFILE ADD CONSTRAINT FK_BIC_PROFILE_FAC  
 FOREIGN  KEY (FACILITY_ID) REFERENCES BILLADMIN.BIC_FACILITY (FACILITY_ID) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.BIC_USER_PROFILE ADD CONSTRAINT FK_BIC_PROFILE_USER  
 FOREIGN  KEY (USER_CODE) REFERENCES BILLADMIN.BIC_USER (USER_CODE) ON DELETE NO ACTION ; 
 
ALTER TABLE BILLADMIN.SRC_DEST_MAP ADD CONSTRAINT FK_SRC_DEST_MAP_ITEM  
 FOREIGN  KEY (ITEM_KEY) REFERENCES BILLADMIN.SRC_SYNC_ITEM (ITEM_KEY) ON DELETE NO ACTION ; 
 

