--*****************************************************
--	Billing Primary Keys
--*****************************************************
--/**---------------------------------------------------------------------------------------
--/* Script			: crt_pk_billing.sql
--/* Author			: Sridevi Tadisetti  
--/* Product		: Infor SCE Suite 
--/* Component		: Billing - Version 12.7
--/* Date			: 18/06/2025        
--/* Description	: Script to insert Primary keys for Billing
--/* RDBMS			: Postgresql
--/* Schema			: Billing
--/* Modification History:
--/*----------------------------------------------------------------------------------------
--/* Modified by	Date			Description    
--/*----------------------------------------------------------------------------------------
--/*
--/*
--/*-----------------------------------------------------------------------------------------

 -- The query should be run at Postgresql with Postgres user

-- Script to create Primary Keys belongs to BILLADMIN role.

ALTER TABLE BILLADMIN.BIC_ACCOUNT 
 ADD PRIMARY KEY (CORP_CODE, DEPT_CODE, ACCT_CODE); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY 
 ADD PRIMARY KEY (ACTIVITY_ID, FACILITY_ID); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FIELD 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_FILTER 
 ADD PRIMARY KEY (FILTER_ID); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TASKS 
 ADD PRIMARY KEY (ACTIVITY_ID, FACILITY_ID, TASK_TYPE); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TRANS 
 ADD PRIMARY KEY (ID); 
 
ALTER TABLE BILLADMIN.BIC_ACTIVITY_TYPE 
 ADD PRIMARY KEY (ACTIVITY_TYPE_KEY); 
 
ALTER TABLE BILLADMIN.BIC_ACTTYPE_FIELD 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_BILLGRP_CUST 
 ADD PRIMARY KEY (CUST_CODE, BILL_GROUP); 
 
ALTER TABLE BILLADMIN.BIC_BILL_GROUP 
 ADD PRIMARY KEY (BILL_GROUP); 
 
ALTER TABLE BILLADMIN.BIC_BILL_GROUP_DET 
 ADD PRIMARY KEY (BILL_GRPDET_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CARRIER_CUST 
 ADD PRIMARY KEY (CUST_CODE, CARRIER_GROUP, CARRIER_CODE); 
 
ALTER TABLE BILLADMIN.BIC_CARRIER_GROUP 
 ADD PRIMARY KEY (CARRIER_GROUP); 
 
ALTER TABLE BILLADMIN.BIC_CARRIER_GRPKEY 
 ADD PRIMARY KEY (CARRIER_GROUP, CARRIER_CODE); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE 
 ADD PRIMARY KEY (CHARGE_NO); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_ACCT 
 ADD PRIMARY KEY (CHARGE_ACCT_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_CODE 
 ADD PRIMARY KEY (CHARGE_CODE); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_DIST 
 ADD PRIMARY KEY (CHARGE_DIST_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CHARGE_UDF 
 ADD PRIMARY KEY (CHARGE_NO, FIELD_LABEL); 
 
ALTER TABLE BILLADMIN.BIC_CHRG_ACCT_DET 
 ADD PRIMARY KEY (CHARGE_DET_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CHRG_CODE_GRP 
 ADD PRIMARY KEY (CHARGE_GROUP); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFIELD 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTFILTER 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_ACTTYPE 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_BILLEVEL 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_CHGTYPE 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_CHGTYPNO 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_COSTALLOC 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_COSTLVL 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_COSTTYPE 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_DISPFMT 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_EVENTSPEC 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_EVENTTYPE 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_FILTFLD 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_INTERTYPE 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_INVSTATUS 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_INVTYPE 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_MATCH 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_MINLEVEL 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_PROFILE 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_REPORT 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_RPTCATG 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_SRCTYPE 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_SYSACT 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CODE_UOMLEVEL 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT 
 ADD PRIMARY KEY (CONTRACT_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CONTRACT_DET 
 ADD PRIMARY KEY (CONTRACT_DET_KEY); 
 
ALTER TABLE BILLADMIN.BIC_CORPORATION 
 ADD PRIMARY KEY (CORP_CODE); 
 
ALTER TABLE BILLADMIN.BIC_COST 
 ADD PRIMARY KEY (COST_NO); 
 
ALTER TABLE BILLADMIN.BIC_COST_BALANCE 
 ADD PRIMARY KEY (BALANCE_KEY); 
 
ALTER TABLE BILLADMIN.BIC_COST_CODE 
 ADD PRIMARY KEY (COST_CODE); 
 
ALTER TABLE BILLADMIN.BIC_COST_DIST 
 ADD PRIMARY KEY (COST_DIST_KEY); 
 
ALTER TABLE BILLADMIN.BIC_COST_GROUP 
 ADD PRIMARY KEY (COST_GROUP); 
 
ALTER TABLE BILLADMIN.BIC_COUNTRY_CURR 
 ADD PRIMARY KEY (COUNTRY_CODE, CURR_CODE); 
 
ALTER TABLE BILLADMIN.BIC_CROSS_REF 
 ADD PRIMARY KEY (CROSS_REF_QUAL, CLIENT_CODE, CROSS_REF_VALUE); 
 
ALTER TABLE BILLADMIN.BIC_CROSS_REF_QUAL 
 ADD PRIMARY KEY (CROSS_REF_QUAL); 
 
ALTER TABLE BILLADMIN.BIC_CURRENCY 
 ADD PRIMARY KEY (CURR_CODE); 
 
ALTER TABLE BILLADMIN.BIC_CURR_HIST 
 ADD PRIMARY KEY (FROM_CURR_CODE, TO_CURR_CODE, EXCHANGE_DATE); 
 
ALTER TABLE BILLADMIN.BIC_DEPARTMENT 
 ADD PRIMARY KEY (CORP_CODE, DEPT_CODE); 
 
ALTER TABLE BILLADMIN.BIC_EVENT 
 ADD PRIMARY KEY (EVENT_KEY); 
 
ALTER TABLE BILLADMIN.BIC_EVENT_GROUP 
 ADD PRIMARY KEY (EVENT_GROUP); 
 
ALTER TABLE BILLADMIN.BIC_FACILITY 
 ADD PRIMARY KEY (FACILITY_ID); 
 
ALTER TABLE BILLADMIN.BIC_FILE 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_FILTER 
 ADD PRIMARY KEY (FILTER_ID); 
 
ALTER TABLE BILLADMIN.BIC_FILTERDETAILS 
 ADD PRIMARY KEY (FILTER_DETAIL_ID); 
 
ALTER TABLE BILLADMIN.BIC_HIST_CHARGE 
 ADD PRIMARY KEY (CHARGE_NO); 
 
ALTER TABLE BILLADMIN.BIC_HIST_CHGDIST 
 ADD PRIMARY KEY (CHARGE_DIST_KEY); 
 
ALTER TABLE BILLADMIN.BIC_HOLIDAY 
 ADD PRIMARY KEY (FACILITY_ID, HOLIDAY_DATE); 
 
ALTER TABLE BILLADMIN.BIC_INTERFACE 
 ADD PRIMARY KEY (CORP_CODE, INTERFACE_CODE); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY 
 ADD PRIMARY KEY (INVENTORY_KEY); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY_BAL 
 ADD PRIMARY KEY (INVENTORY_KEY, BALANCE_DATE); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY_UDF 
 ADD PRIMARY KEY (INVENTORY_KEY, UDF_CODE); 
 
ALTER TABLE BILLADMIN.BIC_INVENTORY_UOM 
 ADD PRIMARY KEY (INVENTORY_KEY, UOM_CODE); 
 
ALTER TABLE BILLADMIN.BIC_INVLOC_BAL 
 ADD PRIMARY KEY (INVENTORY_KEY, BALANCE_DATE, LOC_CODE, LPN); 
 
ALTER TABLE BILLADMIN.BIC_INVOICE 
 ADD PRIMARY KEY (INVOICE_NO); 
 
ALTER TABLE BILLADMIN.BIC_INVOICE_BATCH 
 ADD PRIMARY KEY (BATCH_NO); 
 
ALTER TABLE BILLADMIN.BIC_INVOICE_NO 
 ADD PRIMARY KEY (SEQ_NUM); 
 
ALTER TABLE BILLADMIN.BIC_INVOICE_TERMS 
 ADD PRIMARY KEY (INVOICE_TERMS); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_GROUP 
 ADD PRIMARY KEY (ITEM_GROUP); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_GRPKEY 
 ADD PRIMARY KEY (ITEM_GROUP, ITEM, PKG, CUST_CODE); 
 
ALTER TABLE BILLADMIN.BIC_ITEM_UOM 
 ADD PRIMARY KEY (ITEM, PKG, CUST_CODE, UOM_CODE); 
 
ALTER TABLE BILLADMIN.BIC_LANG_TRANSLATION 
 ADD PRIMARY KEY (SEQ, LOCALE); 
 
ALTER TABLE BILLADMIN.BIC_LOC_GROUP 
 ADD PRIMARY KEY (FACILITY_ID, LOC_GROUP); 
 
ALTER TABLE BILLADMIN.BIC_LOC_GRPKEY 
 ADD PRIMARY KEY (LOC_GROUP_KEY); 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC 
 ADD PRIMARY KEY (MARKUP_KEY); 
 
ALTER TABLE BILLADMIN.BIC_MARKDISC_DET 
 ADD PRIMARY KEY (MARKUP_KEY, CHARGE_CODE, INVOICE_TYPE); 
 
ALTER TABLE BILLADMIN.BIC_MEASURE_CONV 
 ADD PRIMARY KEY (FROM_MEASURE_UOM, TO_MEASURE_UOM); 
 
ALTER TABLE BILLADMIN.BIC_MIN 
 ADD PRIMARY KEY (MIN_KEY); 
 
ALTER TABLE BILLADMIN.BIC_MIN_DETAIL 
 ADD PRIMARY KEY (MIN_KEY, CHARGE_CODE); 
 
ALTER TABLE BILLADMIN.BIC_NONNEG_INV 
 ADD PRIMARY KEY (ORDER_KEY); 
 
ALTER TABLE BILLADMIN.BIC_ORDER_DETAIL 
 ADD PRIMARY KEY (ORDER_DET_KEY); 
 
ALTER TABLE BILLADMIN.BIC_ORDER_HISTORY 
 ADD PRIMARY KEY (ORDER_KEY); 
 
ALTER TABLE BILLADMIN.BIC_PARTNER_CUST 
 ADD PRIMARY KEY (CUST_CODE, PARTNER_GROUP, PARTNER_CODE, MATCH_TYPE); 
 
ALTER TABLE BILLADMIN.BIC_PARTNER_GROUP 
 ADD PRIMARY KEY (PARTNER_GROUP); 
 
ALTER TABLE BILLADMIN.BIC_PARTNER_GRPKEY 
 ADD PRIMARY KEY (PARTNER_GROUP, PARTNER_CODE, MATCH_TYPE); 
 
ALTER TABLE BILLADMIN.BIC_PERIOD 
 ADD PRIMARY KEY (PERIOD_CODE); 
 
ALTER TABLE BILLADMIN.BIC_PERIOD_DETAIL 
 ADD PRIMARY KEY (PERIOD_CODE, FROM_DATE, TO_DATE); 
 
ALTER TABLE BILLADMIN.BIC_PRINTER 
 ADD PRIMARY KEY (SERIAL_KEY); 
 
ALTER TABLE BILLADMIN.BIC_QUERY_TEMP 
 ADD PRIMARY KEY (SERIAL_KEY); 
 
ALTER TABLE BILLADMIN.BIC_RATE 
 ADD PRIMARY KEY (RATE_KEY); 
 
ALTER TABLE BILLADMIN.BIC_RATE_GROUP 
 ADD PRIMARY KEY (RATE_GROUP, EFFECT_DATE, EXPIRE_DATE); 
 
ALTER TABLE BILLADMIN.BIC_RECUR_RULE 
 ADD PRIMARY KEY (RECUR_CODE); 
 
ALTER TABLE BILLADMIN.BIC_REMIT 
 ADD PRIMARY KEY (REMIT_KEY); 
 
ALTER TABLE BILLADMIN.BIC_REPORT 
 ADD PRIMARY KEY (REPORT_KEY); 
 
ALTER TABLE BILLADMIN.BIC_RPTSEND 
 ADD PRIMARY KEY (REPORT_KEY); 
 
ALTER TABLE BILLADMIN.BIC_SQL 
 ADD PRIMARY KEY (SQL_ID); 
 
ALTER TABLE BILLADMIN.BIC_SQL_UTIL 
 ADD PRIMARY KEY (SQL_ID); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM 
 ADD PRIMARY KEY (SYSTEM_ID); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_ACTIVITY 
 ADD PRIMARY KEY (SYSTEM_ACTIVITY, SYSTEM_ID); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_FIELD 
 ADD PRIMARY KEY (ROW_KEY); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_FILTER 
 ADD PRIMARY KEY (SYSTEM_ID, SYSTEM_ACTIVITY, SEQNO); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_TASK 
 ADD PRIMARY KEY (SYSTEM_ID, SYSTEM_ACTIVITY, TASK_TYPE); 
 
ALTER TABLE BILLADMIN.BIC_SYSTEM_TRANS 
 ADD PRIMARY KEY (SYSTEM_ID, SYSTEM_ACTIVITY, ACTIVITY_CLASS, ACTIVITY_OBJECT, ACTIVITY_ACTION, ACTIVITY_TYPE); 
 
ALTER TABLE BILLADMIN.BIC_TAX 
 ADD PRIMARY KEY (TAX_GROUP, TAX_LEVEL, EFFECTIVE_DATE); 
 
ALTER TABLE BILLADMIN.BIC_TAX_DETAIL 
 ADD PRIMARY KEY (TAX_GROUP, TAX_LEVEL, EFFECTIVE_DATE, CHARGE_CODE); 
 
ALTER TABLE BILLADMIN.BIC_TAX_LEVEL 
 ADD PRIMARY KEY (TAX_LEVEL); 
 
ALTER TABLE BILLADMIN.BIC_UOM 
 ADD PRIMARY KEY (UOM_CODE); 
 
ALTER TABLE BILLADMIN.BIC_USER 
 ADD PRIMARY KEY (USER_CODE); 
 
ALTER TABLE BILLADMIN.BIC_USER_BILLGRPS 
 ADD PRIMARY KEY (USERBILLGRPKEY); 
 
ALTER TABLE BILLADMIN.BIC_USER_PROFILE 
 ADD PRIMARY KEY (USER_PROFILE_KEY); 
 
ALTER TABLE BILLADMIN.LOOKUP 
 ADD PRIMARY KEY (LOOKUP_ID); 
 
ALTER TABLE BILLADMIN.LOOKUP_TEXT 
 ADD PRIMARY KEY (LOOKUP_TEXT_ID); 
 
ALTER TABLE BILLADMIN.PM_D_DATE 
 ADD PRIMARY KEY (DATE_KEY); 
 
ALTER TABLE BILLADMIN.PM_SQL_SCHED 
 ADD PRIMARY KEY (SQL_SCHED_ID); 
 
ALTER TABLE BILLADMIN.PM_S_CHARGEALL 
 ADD PRIMARY KEY (CHARGE_YEAR); 
 
ALTER TABLE BILLADMIN.PM_S_CHARGECUST 
 ADD PRIMARY KEY (CUST_CODE, CHARGE_YEAR); 
 
ALTER TABLE BILLADMIN.PM_S_CHARGEDEPT 
 ADD PRIMARY KEY (CUST_CODE, DEPT_CODE, DEPT_NAME, CHARGE_YEAR); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD 
 ADD PRIMARY KEY (CHARGE_DATE, BILLTO_CODE, CUST_CODE, WHSE_CODE, CORP_CODE, DEPT_CODE, CHARGE_TYPE); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1DD_AVG 
 ADD PRIMARY KEY (CHARGE_DATE, WHSE_CODE, CORP_CODE, DEPT_CODE, CHARGE_TYPE); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM 
 ADD PRIMARY KEY (CHARGE_DATE, BILLTO_CODE, CUST_CODE, WHSE_CODE, CORP_CODE, DEPT_CODE, CHARGE_TYPE); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1MM_AVG 
 ADD PRIMARY KEY (CHARGE_DATE, WHSE_CODE, CORP_CODE, DEPT_CODE, CHARGE_TYPE); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW 
 ADD PRIMARY KEY (CHARGE_DATE, BILLTO_CODE, CUST_CODE, WHSE_CODE, CORP_CODE, DEPT_CODE, CHARGE_TYPE); 
 
ALTER TABLE BILLADMIN.PM_S_CHG1WW_AVG 
 ADD PRIMARY KEY (CHARGE_DATE, WHSE_CODE, CORP_CODE, DEPT_CODE, CHARGE_TYPE); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM 
 ADD PRIMARY KEY (CHARGE_DATE, BILLTO_CODE, CUST_CODE, WHSE_CODE, CORP_CODE, DEPT_CODE, ACCT_CODE, CHARGE_CODE, CHARGE_UOM); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2MM_AVG 
 ADD PRIMARY KEY (CHARGE_DATE, WHSE_CODE, CORP_CODE, DEPT_CODE, ACCT_CODE, CHARGE_CODE, CHARGE_UOM); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW 
 ADD PRIMARY KEY (CHARGE_DATE, BILLTO_CODE, CUST_CODE, WHSE_CODE, CORP_CODE, DEPT_CODE, ACCT_CODE, CHARGE_CODE, CHARGE_UOM); 
 
ALTER TABLE BILLADMIN.PM_S_CHG2WW_AVG 
 ADD PRIMARY KEY (CHARGE_DATE, WHSE_CODE, CORP_CODE, DEPT_CODE, ACCT_CODE, CHARGE_CODE, CHARGE_UOM); 
 
ALTER TABLE BILLADMIN.PM_S_CHG3DD 
 ADD PRIMARY KEY (CHARGE_DATE, WHSE_CODE, CORP_CODE, DEPT_CODE, ACCT_CODE); 
 
ALTER TABLE BILLADMIN.SRC_DBS 
 ADD PRIMARY KEY (DBS_KEY); 
 
ALTER TABLE BILLADMIN.SRC_DEST_MAP 
 ADD PRIMARY KEY (ITEM_KEY, DEST_TABLE, DEST_COLUMN); 
 
ALTER TABLE BILLADMIN.SRC_SYNC_ITEM 
 ADD PRIMARY KEY (ITEM_KEY); 
 
ALTER TABLE BILLADMIN.USER_ANONYMIZATION_RULES 
 ADD PRIMARY KEY (TABLE_NAME, COLUMN_NAME, ANONYMIZATION_TYPE); 
 

ALTER TABLE billadmin.BIC_ORDER_PICKDETAIL
 ADD PRIMARY KEY (ORDER_PICKDETAIL_KEY); 


alter table laboradmin.LM_LOC
	add PRIMARY KEY (ID);
